version: '3.4'

services:
  api:
    restart: always
    environment:
      - KLEISTER_API_LOG_LEVEL=debug
      - KLEISTER_API_SERVER_HOST=${KLEISTER_API_SERVER_HOST:-http://localhost:8080}
      - KLEISTER_API_TOKEN_SECRET=${KLEISTER_API_TOKEN_SECRET:-hgJKKJrSzI8pOxCjCnJHvNvK}
      - KLEISTER_API_ADMIN_EMAIL=admin@webhippie.de
    ports:
      - ${KLEISTER_API_SERVER_PORT:-8080}:8080
