workspace:
  base: /srv/app
  path: src/github.com/kleister/kleister-api

pipeline:
  testing:
    image: webhippie/golang:edge
    pull: true
    environment:
      CGO_ENABLED: 1
      TAGS:
      GOPATH: /srv/app
    commands:
      - make clean
      - make vet
      - make varcheck
      - make structcheck
      - make unused
      - make gosimple
      - make unconvert
      - make ineffassign
      - make lint
      - make test
      - make build

  test-mysql:
    image: webhippie/golang:edge
    pull: true
    environment:
      CGO_ENABLED: 1
      TAGS:
      GOPATH: /srv/app
    commands:
      - make test-mysql
    when:
      event: [ push ]

  test-pgsql:
    image: webhippie/golang:edge
    pull: true
    environment:
      CGO_ENABLED: 1
      TAGS:
      GOPATH: /srv/app
    commands:
      - make test-pgsql
    when:
      event: [ push ]

  updater:
    image: karalabe/xgo-latest:latest
    pull: true
    environment:
      CGO_ENABLED: 1
      TAGS:
      GOPATH: /srv/app
    commands:
      - make release
    when:
      event: [ push, tag ]
      branch: [ master, release/*, refs/tags/* ]

  # coverage:
  #   image: plugins/coverage
  #   server: https://coverage.gitea.io
  #   when:
  #     event: [ push, tag, pull_request ]

  docker:
    image: plugins/docker
    repo: kleister/kleister-api
    tags: [ '${DRONE_TAG##v}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    repo: kleister/kleister-api
    tags: [ '${DRONE_BRANCH##release/v}' ]
    when:
      event: [ push ]
      branch: [ release/* ]

  docker:
    image: plugins/docker
    repo: kleister/kleister-api
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-api/${DRONE_TAG##v}
  #   recursive: true
  #   delete: true
  #   when:
  #     event: [ tag ]
  #     branch: [ refs/tags/* ]

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-api/${DRONE_TAG##release/v}
  #   recursive: true
  #   delete: true
  #   when:
  #     event: [ push ]
  #     branch: [ release/* ]

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-api/master
  #   recursive: true
  #   delete: true
  #   when:
  #     event: [ push ]
  #     branch: [ master ]

  github:
    image: plugins/github-release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  gitter:
    image: plugins/gitter

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    when:
      event: [ push ]

  pgsql:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=test
    when:
      event: [ push ]
