workspace:
  base: /srv/app
  path: src/github.com/kleister/kleister-api

pipeline:
  testing:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=1
      - TAGS=
      - GOPATH=/srv/app
    commands:
      - make clean
      - make vet
      - make varcheck
      - make structcheck
      - make unconvert
      - make ineffassign
      - make lint
      - make test
      - make build

  testing-mysql:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=1
      - TAGS=
      - GOPATH=/srv/app
    commands:
      - make test-mysql
    when:
      event: [ push ]

  testing-pgsql:
    image: webhippie/golang:edge
    pull: true
    environment:
      - CGO_ENABLED=1
      - TAGS=
      - GOPATH=/srv/app
    commands:
      - make test-pgsql
    when:
      event: [ push ]

  release:
    image: karalabe/xgo-latest:latest
    pull: true
    environment:
      - CGO_ENABLED=1
      - TAGS=
      - GOPATH=/srv/app
    commands:
      - make release
    when:
      event: [ push, tag ]
      branch: [ master, release/*, refs/tags/* ]

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-api
    tags: [ '${DRONE_TAG##v}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-api
    tags: [ '${DRONE_BRANCH##release/v}' ]
    when:
      event: [ push ]
      branch: [ release/* ]

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kleister/kleister-api
    tags: [ 'latest' ]
    when:
      event: [ push ]
      branch: [ master ]

  microbadger:
    image: zyclonite/drone-webhook
    secrets:
      - source: microbadger_token
        target: plugin_webhook
    when:
      event: [ push, tag ]
      branch: [ master, release/*, refs/tags/* ]
      status: [ success ]

  archive:
    image: plugins/s3
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /kleister/api/${DRONE_TAG##v}
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  archive:
    image: plugins/s3
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /kleister/api/${DRONE_TAG##release/v}
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ push ]
      branch: [ release/* ]

  archive:
    image: plugins/s3
    secrets: [ s3_endpoint, aws_access_key_id, aws_secret_access_key, s3_bucket ]
    source: dist/release/*
    target: /kleister/api/master
    strip_prefix: dist/release/
    path_style: true
    when:
      event: [ push ]
      branch: [ master ]

  github:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  gitter:
    image: plugins/gitter
    secrets: [ gitter_webhook ]

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    when:
      event: [ push ]

  pgsql:
    image: postgres:9.5
    environment:
      - POSTGRES_DB=test
    when:
      event: [ push ]
