build:
  general:
    image: webhippie/golang:latest
    commands:
      - make clean
      - make deps
      - make vet
      - make lint
      - make build
      - make test

  updater:
    image: webhippie/golang:latest
    commands:
      - make release
      - make updater
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

publish:
  coverage:
    server: http://coverage.dronehippie.de
    token: $$GITHUB_APIKEY
    when:
      branch: master

  rsync:
    user: deploy
    host: dl.webhippie.de
    source: dist/release/
    target: $$BASE_PATH/solder-api/master
    recursive: true
    delete: true
    when:
      branch: master

  rsync:
    user: deploy
    host: dl.webhippie.de
    source: dist/release/
    target: $$BASE_PATH/solder-api/$$TAG
    recursive: true
    delete: true
    when:
      event: tag

  rsync:
    user: deploy
    host: dl.webhippie.de
    source: dist/latest/
    target: $$BASE_PATH/solder-api/latest
    recursive: true
    delete: true
    when:
      event: tag

  rsync:
    user: deploy
    host: dl.webhippie.de
    source: dist/publish/
    target: $$BASE_PATH/solder-api/updates
    recursive: true
    delete: false
    when:
      event: tag

  github_release:
    api_key: $$GITHUB_APIKEY
    files:
      - dist/release/*
    when:
      event: tag

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    storage_driver: overlay
    repo: solderapp/solder-api
    tag: $$TAG
    when:
      event: tag

  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    storage_driver: overlay
    repo: solderapp/solder-api
    tag: latest
    when:
      branch: master

notify:
  gitter:
    webhook:
      - $$GITTER_WEBHOOK
