workspace:
  base: /srv/app
  path: src/github.com/kleister/kleister-api

pipeline:
  testing:
    image: webhippie/golang:edge
    pull: true
    commands:
      - make clean
      - make vet
      - make lint
      - make test
      - make build

  updater:
    image: webhippie/golang:edge
    commands:
      - make publish
    when:
      event: [ push, tag ]
      branch: [ master, refs/tags/* ]

  coverage:
    image: plugins/coverage
    server: http://coverage.dronehippie.de

  docker1:
    image: plugins/docker
    repo: kleister/kleister-api
    tags: [ '${TAG}' ]
    when:
      event: tag
      branch: refs/tags/*

  docker2:
    image: plugins/docker
    repo: kleister/kleister-api
    tags: [ 'latest' ]
    when:
      event: push
      branch: master

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-api/master
  #   recursive: true
  #   delete: true
  #   when:
  #     event: push
  #     branch: master

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/release/
  #   target: /usr/share/webapps/dl/public_html/kleister-api/$$TAG
  #   recursive: true
  #   delete: true
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # rsync:
  #   image: plugins/rsync
  #   user: deploy
  #   host: dl.webhippie.de
  #   source: dist/latest/
  #   target: /usr/share/webapps/dl/public_html/kleister-api/latest
  #   recursive: true
  #   delete: true
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  # github_release:
  #   image: plugins/github-release
  #   files:
  #     - dist/release/*
  #   when:
  #     event: tag
  #     branch: refs/tags/*

  gitter:
    image: plugins/gitter
