# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - task fe:install
    - task fe:build

builds:
  - id: api
    main: ./cmd/kleister-api
    binary: kleister-api
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X "github.com/kleister/kleister-api/pkg/version.String={{.Version}}" -X "github.com/kleister/kleister-api/pkg/version.Revision={{.Commit}}" -X "github.com/kleister/kleister-api/pkg/version.Date={{.Date}}"
    tags:
      - netgo
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
      - arm
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm

archives:
  - id: api
    ids:
      - api
    name_template: "kleister-api-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - CHANGELOG.md
      - src: cmd/kleister-api/README.md
        dst: README.md

nfpms:
  - id: api
    ids:
      - api
    package_name: kleister-api
    file_name_template: "kleister-api-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}"
    vendor: Kleister
    homepage: https://kleister.eu
    maintainer: Thomas Boerger <thomas@webhippie.de>
    description: |-
      Server to manage mod packs for Minecraft
    license: Apache 2.0
    formats:
      - deb
      - rpm
    contents:
      - src: packaging/systemd/api.service
        dst: /usr/lib/systemd/system/kleister-api.service
      - src: packaging/systemd/api.env
        dst: /etc/sysconfig/kleister-api
        packager: rpm
      - src: packaging/systemd/api.env
        dst: /etc/default/kleister-api
        packager: deb
      - src: packaging/config/api.yaml
        dst: /etc/kleister/api.yaml
        type: config|noreplace
      - dst: /var/lib/kleister
        type: dir
    scripts:
      preinstall: packaging/scripts/preinstall.sh
      postinstall: packaging/scripts/postinstall.sh
      preremove: packaging/scripts/preremove.sh
      postremove: packaging/scripts/postremove.sh

signs:
  - id: archives
    signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: archive
    args:
      - --batch
      - --armor
      - --local-user
      - 7F494434AC882A11606CD1CDCBAFAA16B09C86A1
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
  - id: packages
    signature: "${artifact}.asc"
    cmd: gpg2
    artifacts: package
    args:
      - --batch
      - --armor
      - --local-user
      - 7F494434AC882A11606CD1CDCBAFAA16B09C86A1
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

snapshot:
  version_template: testing

changelog:
  disable: true

checksum:
  disable: false
  split: true
