version: '3.4'

volumes:
  mariadb:

services:
  api:
    environment:
      - KLEISTER_API_DATABASE_DRIVER=mysql
      - KLEISTER_API_DATABASE_ADDRESS=db
      - KLEISTER_API_DATABASE_PORT=3306
      - KLEISTER_API_DATABASE_USERNAME=kleister
      - KLEISTER_API_DATABASE_PASSWORD=kleister
      - KLEISTER_API_DATABASE_NAME=kleister
    depends_on:
      - db

  db:
    image: mariadb:10.8
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=kleister
      - MARIADB_PASSWORD=kleister
      - MARIADB_DATABASE=kleister
    volumes:
      - mariadb:/var/lib/mysql
