version: '3.4'

volumes:
  postgres:

services:
  api:
    environment:
      - KLEISTER_API_DATABASE_DRIVER=postgres
      - KLEISTER_API_DATABASE_ADDRESS=db
      - KLEISTER_API_DATABASE_PORT=5432
      - KLEISTER_API_DATABASE_USERNAME=kleister
      - KLEISTER_API_DATABASE_PASSWORD=kleister
      - KLEISTER_API_DATABASE_NAME=kleister
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    environment:
      - POSTGRES_USER=kleister
      - POSTGRES_PASSWORD=kleister
      - POSTGRES_DB=kleister
    volumes:
      - postgres:/var/lib/postgresql
