// Code generated by go-swagger; DO NOT EDIT.

package forge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AppendForgeToBuildHandlerFunc turns a function with the right signature into a append forge to build handler
type AppendForgeToBuildHandlerFunc func(AppendForgeToBuildParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AppendForgeToBuildHandlerFunc) Handle(params AppendForgeToBuildParams) middleware.Responder {
	return fn(params)
}

// AppendForgeToBuildHandler interface for that can handle valid append forge to build params
type AppendForgeToBuildHandler interface {
	Handle(AppendForgeToBuildParams) middleware.Responder
}

// NewAppendForgeToBuild creates a new http.Handler for the append forge to build operation
func NewAppendForgeToBuild(ctx *middleware.Context, handler AppendForgeToBuildHandler) *AppendForgeToBuild {
	return &AppendForgeToBuild{Context: ctx, Handler: handler}
}

/*AppendForgeToBuild swagger:route POST /forge/{forgeID}/builds forge appendForgeToBuild

Assign a build to a Forge version

*/
type AppendForgeToBuild struct {
	Context *middleware.Context
	Handler AppendForgeToBuildHandler
}

func (o *AppendForgeToBuild) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAppendForgeToBuildParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
