// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: profile/v1/profile.proto

package profilev1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/kleister/kleister-api/pkg/service/profile/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// ProfileServiceName is the fully-qualified name of the ProfileService service.
	ProfileServiceName = "profile.v1.ProfileService"
)

// ProfileServiceClient is a client for the profile.v1.ProfileService service.
type ProfileServiceClient interface {
	Show(context.Context, *connect_go.Request[v1.ShowRequest]) (*connect_go.Response[v1.ShowResponse], error)
	Update(context.Context, *connect_go.Request[v1.UpdateRequest]) (*connect_go.Response[v1.UpdateResponse], error)
	ListTeams(context.Context, *connect_go.Request[v1.ListTeamsRequest]) (*connect_go.Response[v1.ListTeamsResponse], error)
	ListPacks(context.Context, *connect_go.Request[v1.ListPacksRequest]) (*connect_go.Response[v1.ListPacksResponse], error)
	ListMods(context.Context, *connect_go.Request[v1.ListModsRequest]) (*connect_go.Response[v1.ListModsResponse], error)
}

// NewProfileServiceClient constructs a client for the profile.v1.ProfileService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProfileServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) ProfileServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &profileServiceClient{
		show: connect_go.NewClient[v1.ShowRequest, v1.ShowResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/Show",
			opts...,
		),
		update: connect_go.NewClient[v1.UpdateRequest, v1.UpdateResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/Update",
			opts...,
		),
		listTeams: connect_go.NewClient[v1.ListTeamsRequest, v1.ListTeamsResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/ListTeams",
			opts...,
		),
		listPacks: connect_go.NewClient[v1.ListPacksRequest, v1.ListPacksResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/ListPacks",
			opts...,
		),
		listMods: connect_go.NewClient[v1.ListModsRequest, v1.ListModsResponse](
			httpClient,
			baseURL+"/profile.v1.ProfileService/ListMods",
			opts...,
		),
	}
}

// profileServiceClient implements ProfileServiceClient.
type profileServiceClient struct {
	show      *connect_go.Client[v1.ShowRequest, v1.ShowResponse]
	update    *connect_go.Client[v1.UpdateRequest, v1.UpdateResponse]
	listTeams *connect_go.Client[v1.ListTeamsRequest, v1.ListTeamsResponse]
	listPacks *connect_go.Client[v1.ListPacksRequest, v1.ListPacksResponse]
	listMods  *connect_go.Client[v1.ListModsRequest, v1.ListModsResponse]
}

// Show calls profile.v1.ProfileService.Show.
func (c *profileServiceClient) Show(ctx context.Context, req *connect_go.Request[v1.ShowRequest]) (*connect_go.Response[v1.ShowResponse], error) {
	return c.show.CallUnary(ctx, req)
}

// Update calls profile.v1.ProfileService.Update.
func (c *profileServiceClient) Update(ctx context.Context, req *connect_go.Request[v1.UpdateRequest]) (*connect_go.Response[v1.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// ListTeams calls profile.v1.ProfileService.ListTeams.
func (c *profileServiceClient) ListTeams(ctx context.Context, req *connect_go.Request[v1.ListTeamsRequest]) (*connect_go.Response[v1.ListTeamsResponse], error) {
	return c.listTeams.CallUnary(ctx, req)
}

// ListPacks calls profile.v1.ProfileService.ListPacks.
func (c *profileServiceClient) ListPacks(ctx context.Context, req *connect_go.Request[v1.ListPacksRequest]) (*connect_go.Response[v1.ListPacksResponse], error) {
	return c.listPacks.CallUnary(ctx, req)
}

// ListMods calls profile.v1.ProfileService.ListMods.
func (c *profileServiceClient) ListMods(ctx context.Context, req *connect_go.Request[v1.ListModsRequest]) (*connect_go.Response[v1.ListModsResponse], error) {
	return c.listMods.CallUnary(ctx, req)
}

// ProfileServiceHandler is an implementation of the profile.v1.ProfileService service.
type ProfileServiceHandler interface {
	Show(context.Context, *connect_go.Request[v1.ShowRequest]) (*connect_go.Response[v1.ShowResponse], error)
	Update(context.Context, *connect_go.Request[v1.UpdateRequest]) (*connect_go.Response[v1.UpdateResponse], error)
	ListTeams(context.Context, *connect_go.Request[v1.ListTeamsRequest]) (*connect_go.Response[v1.ListTeamsResponse], error)
	ListPacks(context.Context, *connect_go.Request[v1.ListPacksRequest]) (*connect_go.Response[v1.ListPacksResponse], error)
	ListMods(context.Context, *connect_go.Request[v1.ListModsRequest]) (*connect_go.Response[v1.ListModsResponse], error)
}

// NewProfileServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProfileServiceHandler(svc ProfileServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/profile.v1.ProfileService/Show", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/Show",
		svc.Show,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/Update", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/Update",
		svc.Update,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/ListTeams", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/ListTeams",
		svc.ListTeams,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/ListPacks", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/ListPacks",
		svc.ListPacks,
		opts...,
	))
	mux.Handle("/profile.v1.ProfileService/ListMods", connect_go.NewUnaryHandler(
		"/profile.v1.ProfileService/ListMods",
		svc.ListMods,
		opts...,
	))
	return "/profile.v1.ProfileService/", mux
}

// UnimplementedProfileServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProfileServiceHandler struct{}

func (UnimplementedProfileServiceHandler) Show(context.Context, *connect_go.Request[v1.ShowRequest]) (*connect_go.Response[v1.ShowResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.Show is not implemented"))
}

func (UnimplementedProfileServiceHandler) Update(context.Context, *connect_go.Request[v1.UpdateRequest]) (*connect_go.Response[v1.UpdateResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.Update is not implemented"))
}

func (UnimplementedProfileServiceHandler) ListTeams(context.Context, *connect_go.Request[v1.ListTeamsRequest]) (*connect_go.Response[v1.ListTeamsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.ListTeams is not implemented"))
}

func (UnimplementedProfileServiceHandler) ListPacks(context.Context, *connect_go.Request[v1.ListPacksRequest]) (*connect_go.Response[v1.ListPacksResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.ListPacks is not implemented"))
}

func (UnimplementedProfileServiceHandler) ListMods(context.Context, *connect_go.Request[v1.ListModsRequest]) (*connect_go.Response[v1.ListModsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("profile.v1.ProfileService.ListMods is not implemented"))
}
