// Code generated by go-swagger; DO NOT EDIT.

package minecraft

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// ListMinecraftsHandlerFunc turns a function with the right signature into a list minecrafts handler
type ListMinecraftsHandlerFunc func(ListMinecraftsParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn ListMinecraftsHandlerFunc) Handle(params ListMinecraftsParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// ListMinecraftsHandler interface for that can handle valid list minecrafts params
type ListMinecraftsHandler interface {
	Handle(ListMinecraftsParams, *models.User) middleware.Responder
}

// NewListMinecrafts creates a new http.Handler for the list minecrafts operation
func NewListMinecrafts(ctx *middleware.Context, handler ListMinecraftsHandler) *ListMinecrafts {
	return &ListMinecrafts{Context: ctx, Handler: handler}
}

/* ListMinecrafts swagger:route GET /minecraft minecraft listMinecrafts

Fetch the available Minecraft versions

*/
type ListMinecrafts struct {
	Context *middleware.Context
	Handler ListMinecraftsHandler
}

func (o *ListMinecrafts) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListMinecraftsParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
