// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// AppendUserToModHandlerFunc turns a function with the right signature into a append user to mod handler
type AppendUserToModHandlerFunc func(AppendUserToModParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn AppendUserToModHandlerFunc) Handle(params AppendUserToModParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// AppendUserToModHandler interface for that can handle valid append user to mod params
type AppendUserToModHandler interface {
	Handle(AppendUserToModParams, *models.User) middleware.Responder
}

// NewAppendUserToMod creates a new http.Handler for the append user to mod operation
func NewAppendUserToMod(ctx *middleware.Context, handler AppendUserToModHandler) *AppendUserToMod {
	return &AppendUserToMod{Context: ctx, Handler: handler}
}

/* AppendUserToMod swagger:route POST /users/{user_id}/mods user appendUserToMod

Assign a mod to user

*/
type AppendUserToMod struct {
	Context *middleware.Context
	Handler AppendUserToModHandler
}

func (o *AppendUserToMod) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAppendUserToModParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
