// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PermitUserModHandlerFunc turns a function with the right signature into a permit user mod handler
type PermitUserModHandlerFunc func(PermitUserModParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PermitUserModHandlerFunc) Handle(params PermitUserModParams) middleware.Responder {
	return fn(params)
}

// PermitUserModHandler interface for that can handle valid permit user mod params
type PermitUserModHandler interface {
	Handle(PermitUserModParams) middleware.Responder
}

// NewPermitUserMod creates a new http.Handler for the permit user mod operation
func NewPermitUserMod(ctx *middleware.Context, handler PermitUserModHandler) *PermitUserMod {
	return &PermitUserMod{Context: ctx, Handler: handler}
}

/*PermitUserMod swagger:route PUT /users/{userID}/mods user permitUserMod

Update mod perms for user

*/
type PermitUserMod struct {
	Context *middleware.Context
	Handler PermitUserModHandler
}

func (o *PermitUserMod) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPermitUserModParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
