// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// PermitUserPackHandlerFunc turns a function with the right signature into a permit user pack handler
type PermitUserPackHandlerFunc func(PermitUserPackParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PermitUserPackHandlerFunc) Handle(params PermitUserPackParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PermitUserPackHandler interface for that can handle valid permit user pack params
type PermitUserPackHandler interface {
	Handle(PermitUserPackParams, *models.User) middleware.Responder
}

// NewPermitUserPack creates a new http.Handler for the permit user pack operation
func NewPermitUserPack(ctx *middleware.Context, handler PermitUserPackHandler) *PermitUserPack {
	return &PermitUserPack{Context: ctx, Handler: handler}
}

/*
	PermitUserPack swagger:route PUT /users/{user_id}/packs user permitUserPack

Update pack perms for user
*/
type PermitUserPack struct {
	Context *middleware.Context
	Handler PermitUserPackHandler
}

func (o *PermitUserPack) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPermitUserPackParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
