// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// PermitUserModOKCode is the HTTP code returned for type PermitUserModOK
const PermitUserModOKCode int = 200

/*
PermitUserModOK Plain success message

swagger:response permitUserModOK
*/
type PermitUserModOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPermitUserModOK creates PermitUserModOK with default headers values
func NewPermitUserModOK() *PermitUserModOK {

	return &PermitUserModOK{}
}

// WithPayload adds the payload to the permit user mod o k response
func (o *PermitUserModOK) WithPayload(payload *models.GeneralError) *PermitUserModOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the permit user mod o k response
func (o *PermitUserModOK) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PermitUserModOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PermitUserModForbiddenCode is the HTTP code returned for type PermitUserModForbidden
const PermitUserModForbiddenCode int = 403

/*
PermitUserModForbidden User is not authorized

swagger:response permitUserModForbidden
*/
type PermitUserModForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPermitUserModForbidden creates PermitUserModForbidden with default headers values
func NewPermitUserModForbidden() *PermitUserModForbidden {

	return &PermitUserModForbidden{}
}

// WithPayload adds the payload to the permit user mod forbidden response
func (o *PermitUserModForbidden) WithPayload(payload *models.GeneralError) *PermitUserModForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the permit user mod forbidden response
func (o *PermitUserModForbidden) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PermitUserModForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PermitUserModNotFoundCode is the HTTP code returned for type PermitUserModNotFound
const PermitUserModNotFoundCode int = 404

/*
PermitUserModNotFound User or mod not found

swagger:response permitUserModNotFound
*/
type PermitUserModNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPermitUserModNotFound creates PermitUserModNotFound with default headers values
func NewPermitUserModNotFound() *PermitUserModNotFound {

	return &PermitUserModNotFound{}
}

// WithPayload adds the payload to the permit user mod not found response
func (o *PermitUserModNotFound) WithPayload(payload *models.GeneralError) *PermitUserModNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the permit user mod not found response
func (o *PermitUserModNotFound) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PermitUserModNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PermitUserModPreconditionFailedCode is the HTTP code returned for type PermitUserModPreconditionFailed
const PermitUserModPreconditionFailedCode int = 412

/*
PermitUserModPreconditionFailed Mod is not assigned

swagger:response permitUserModPreconditionFailed
*/
type PermitUserModPreconditionFailed struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPermitUserModPreconditionFailed creates PermitUserModPreconditionFailed with default headers values
func NewPermitUserModPreconditionFailed() *PermitUserModPreconditionFailed {

	return &PermitUserModPreconditionFailed{}
}

// WithPayload adds the payload to the permit user mod precondition failed response
func (o *PermitUserModPreconditionFailed) WithPayload(payload *models.GeneralError) *PermitUserModPreconditionFailed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the permit user mod precondition failed response
func (o *PermitUserModPreconditionFailed) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PermitUserModPreconditionFailed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(412)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PermitUserModUnprocessableEntityCode is the HTTP code returned for type PermitUserModUnprocessableEntity
const PermitUserModUnprocessableEntityCode int = 422

/*
PermitUserModUnprocessableEntity Failed to validate request

swagger:response permitUserModUnprocessableEntity
*/
type PermitUserModUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.ValidationError `json:"body,omitempty"`
}

// NewPermitUserModUnprocessableEntity creates PermitUserModUnprocessableEntity with default headers values
func NewPermitUserModUnprocessableEntity() *PermitUserModUnprocessableEntity {

	return &PermitUserModUnprocessableEntity{}
}

// WithPayload adds the payload to the permit user mod unprocessable entity response
func (o *PermitUserModUnprocessableEntity) WithPayload(payload *models.ValidationError) *PermitUserModUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the permit user mod unprocessable entity response
func (o *PermitUserModUnprocessableEntity) SetPayload(payload *models.ValidationError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PermitUserModUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PermitUserModDefault Some error unrelated to the handler

swagger:response permitUserModDefault
*/
type PermitUserModDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPermitUserModDefault creates PermitUserModDefault with default headers values
func NewPermitUserModDefault(code int) *PermitUserModDefault {
	if code <= 0 {
		code = 500
	}

	return &PermitUserModDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the permit user mod default response
func (o *PermitUserModDefault) WithStatusCode(code int) *PermitUserModDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the permit user mod default response
func (o *PermitUserModDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the permit user mod default response
func (o *PermitUserModDefault) WithPayload(payload *models.GeneralError) *PermitUserModDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the permit user mod default response
func (o *PermitUserModDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PermitUserModDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
