// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserPackAppendHandlerFunc turns a function with the right signature into a user pack append handler
type UserPackAppendHandlerFunc func(UserPackAppendParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserPackAppendHandlerFunc) Handle(params UserPackAppendParams) middleware.Responder {
	return fn(params)
}

// UserPackAppendHandler interface for that can handle valid user pack append params
type UserPackAppendHandler interface {
	Handle(UserPackAppendParams) middleware.Responder
}

// NewUserPackAppend creates a new http.Handler for the user pack append operation
func NewUserPackAppend(ctx *middleware.Context, handler UserPackAppendHandler) *UserPackAppend {
	return &UserPackAppend{Context: ctx, Handler: handler}
}

/*UserPackAppend swagger:route POST /users/{userID}/packs user userPackAppend

Assign a pack to user

*/
type UserPackAppend struct {
	Context *middleware.Context
	Handler UserPackAppendHandler
}

func (o *UserPackAppend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserPackAppendParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
