// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// UserModAppendHandlerFunc turns a function with the right signature into a user mod append handler
type UserModAppendHandlerFunc func(UserModAppendParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UserModAppendHandlerFunc) Handle(params UserModAppendParams) middleware.Responder {
	return fn(params)
}

// UserModAppendHandler interface for that can handle valid user mod append params
type UserModAppendHandler interface {
	Handle(UserModAppendParams) middleware.Responder
}

// NewUserModAppend creates a new http.Handler for the user mod append operation
func NewUserModAppend(ctx *middleware.Context, handler UserModAppendHandler) *UserModAppend {
	return &UserModAppend{Context: ctx, Handler: handler}
}

/*UserModAppend swagger:route POST /users/{userID}/mods user userModAppend

Assign a mod to user

*/
type UserModAppend struct {
	Context *middleware.Context
	Handler UserModAppendHandler
}

func (o *UserModAppend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUserModAppendParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
