FROM i386/alpine:3.20 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 8000 8080
VOLUME ["/var/lib/kleister"]
ENTRYPOINT ["/usr/bin/kleister-api"]
CMD ["server"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

ENV KLEISTER_API_DB_DSN sqlite:///var/lib/kleister/database.sqlite3
ENV KLEISTER_API_UPLOAD_DSN file:///var/lib/kleister/uploads

COPY bin/kleister-api /usr/bin/kleister-api
