FROM i386/alpine:3.21

RUN apk add --no-cache ca-certificates mailcap && \
    addgroup -g 1337 kleister && \
    adduser -D -u 1337 -h /var/lib/kleister -G kleister kleister

EXPOSE 8000 8080
VOLUME ["/var/lib/kleister"]
ENTRYPOINT ["/usr/bin/kleister-api"]
CMD ["server"]

ENV KLEISTER_API_DATABASE_DSN sqlite:///var/lib/kleister/database.sqlite3
ENV KLEISTER_API_UPLOAD_DSN file:///var/lib/kleister/uploads

COPY bin/kleister-api /usr/bin/kleister-api
WORKDIR /var/lib/kleister
USER kleister
