FROM amd64/alpine:3.17 AS build
RUN apk add --no-cache ca-certificates mailcap

FROM scratch

EXPOSE 8080 8090
VOLUME ["/var/lib/kleister"]
ENTRYPOINT ["/usr/bin/kleister-api"]
CMD ["server"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /etc/mime.types /etc/

ENV KLEISTER_API_DB_DSN boltdb:///var/lib/kleister/database.db
ENV KLEISTER_API_UPLOAD_DSN file:///var/lib/kleister/uploads

COPY bin/kleister-api /usr/bin/kleister-api
