# escape=`
FROM microsoft/nanoserver:10.0.14393.2430

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" `
  org.label-schema.name="Kleister API" `
  org.label-schema.vendor="Thomas Boerger" `
  org.label-schema.schema-version="1.0"

EXPOSE 8080 8090
VOLUME c:\kleister

ENV KLEISTER_API_DB_DSN boltdb:///kleister/database.db
ENV KLEISTER_API_UPLOAD_DSN file:///kleister/uploads

ENTRYPOINT ["c:\\kleister-api.exe"]
CMD ["server"]

COPY bin/kleister-api.exe c:\kleister-api.exe
