version: '3.4'

volumes:
  minio:

services:
  api:
    environment:
      - KLEISTER_API_UPLOAD_DRIVER=s3
      - KLEISTER_API_UPLOAD_ENDPOINT=minio:9000
      - KLEISTER_API_UPLOAD_BUCKET=kleister
      - KLEISTER_API_UPLOAD_REGION=us-east-1
      - KLEISTER_API_UPLOAD_ACCESS=minioadmin
      - KLEISTER_API_UPLOAD_SECRET=minioadmin
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    restart: always
    command:
      - minio
      - server
      - /var/lib/minio
    ports:
      - 9000:9000
    volumes:
      - minio:/var/lib/minio
