// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AppendVersionToBuildHandlerFunc turns a function with the right signature into a append version to build handler
type AppendVersionToBuildHandlerFunc func(AppendVersionToBuildParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AppendVersionToBuildHandlerFunc) Handle(params AppendVersionToBuildParams) middleware.Responder {
	return fn(params)
}

// AppendVersionToBuildHandler interface for that can handle valid append version to build params
type AppendVersionToBuildHandler interface {
	Handle(AppendVersionToBuildParams) middleware.Responder
}

// NewAppendVersionToBuild creates a new http.Handler for the append version to build operation
func NewAppendVersionToBuild(ctx *middleware.Context, handler AppendVersionToBuildHandler) *AppendVersionToBuild {
	return &AppendVersionToBuild{Context: ctx, Handler: handler}
}

/*AppendVersionToBuild swagger:route POST /mods/{modID}/versions/{versionID}/builds mod appendVersionToBuild

Assign a build to a version

*/
type AppendVersionToBuild struct {
	Context *middleware.Context
	Handler AppendVersionToBuildHandler
}

func (o *AppendVersionToBuild) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAppendVersionToBuildParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
