// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// CreateModHandlerFunc turns a function with the right signature into a create mod handler
type CreateModHandlerFunc func(CreateModParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateModHandlerFunc) Handle(params CreateModParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreateModHandler interface for that can handle valid create mod params
type CreateModHandler interface {
	Handle(CreateModParams, *models.User) middleware.Responder
}

// NewCreateMod creates a new http.Handler for the create mod operation
func NewCreateMod(ctx *middleware.Context, handler CreateModHandler) *CreateMod {
	return &CreateMod{Context: ctx, Handler: handler}
}

/* CreateMod swagger:route POST /mods mod createMod

Create a new mod

*/
type CreateMod struct {
	Context *middleware.Context
	Handler CreateModHandler
}

func (o *CreateMod) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateModParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
