// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// CreateVersionHandlerFunc turns a function with the right signature into a create version handler
type CreateVersionHandlerFunc func(CreateVersionParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateVersionHandlerFunc) Handle(params CreateVersionParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// CreateVersionHandler interface for that can handle valid create version params
type CreateVersionHandler interface {
	Handle(CreateVersionParams, *models.User) middleware.Responder
}

// NewCreateVersion creates a new http.Handler for the create version operation
func NewCreateVersion(ctx *middleware.Context, handler CreateVersionHandler) *CreateVersion {
	return &CreateVersion{Context: ctx, Handler: handler}
}

/* CreateVersion swagger:route POST /mods/{mod_id}/versions mod createVersion

Create a new version for a mod

*/
type CreateVersion struct {
	Context *middleware.Context
	Handler CreateVersionHandler
}

func (o *CreateVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateVersionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
