// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewListVersionBuildsParams creates a new ListVersionBuildsParams object
//
// There are no default values defined in the spec.
func NewListVersionBuildsParams() ListVersionBuildsParams {

	return ListVersionBuildsParams{}
}

// ListVersionBuildsParams contains all the bound params for the list version builds operation
// typically these are obtained from a http.Request
//
// swagger:parameters ListVersionBuilds
type ListVersionBuildsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*A mod UUID or slug
	  Required: true
	  In: path
	*/
	ModID string
	/*A version UUID or slug
	  Required: true
	  In: path
	*/
	VersionID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListVersionBuildsParams() beforehand.
func (o *ListVersionBuildsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rModID, rhkModID, _ := route.Params.GetOK("mod_id")
	if err := o.bindModID(rModID, rhkModID, route.Formats); err != nil {
		res = append(res, err)
	}

	rVersionID, rhkVersionID, _ := route.Params.GetOK("version_id")
	if err := o.bindVersionID(rVersionID, rhkVersionID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindModID binds and validates parameter ModID from path.
func (o *ListVersionBuildsParams) bindModID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ModID = raw

	return nil
}

// bindVersionID binds and validates parameter VersionID from path.
func (o *ListVersionBuildsParams) bindVersionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.VersionID = raw

	return nil
}
