// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListVersionBuildsHandlerFunc turns a function with the right signature into a list version builds handler
type ListVersionBuildsHandlerFunc func(ListVersionBuildsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListVersionBuildsHandlerFunc) Handle(params ListVersionBuildsParams) middleware.Responder {
	return fn(params)
}

// ListVersionBuildsHandler interface for that can handle valid list version builds params
type ListVersionBuildsHandler interface {
	Handle(ListVersionBuildsParams) middleware.Responder
}

// NewListVersionBuilds creates a new http.Handler for the list version builds operation
func NewListVersionBuilds(ctx *middleware.Context, handler ListVersionBuildsHandler) *ListVersionBuilds {
	return &ListVersionBuilds{Context: ctx, Handler: handler}
}

/*ListVersionBuilds swagger:route GET /mods/{modID}/versions/{versionID}/builds mod listVersionBuilds

Fetch all builds assigned to version

*/
type ListVersionBuilds struct {
	Context *middleware.Context
	Handler ListVersionBuildsHandler
}

func (o *ListVersionBuilds) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListVersionBuildsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
