// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ModDeleteHandlerFunc turns a function with the right signature into a mod delete handler
type ModDeleteHandlerFunc func(ModDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ModDeleteHandlerFunc) Handle(params ModDeleteParams) middleware.Responder {
	return fn(params)
}

// ModDeleteHandler interface for that can handle valid mod delete params
type ModDeleteHandler interface {
	Handle(ModDeleteParams) middleware.Responder
}

// NewModDelete creates a new http.Handler for the mod delete operation
func NewModDelete(ctx *middleware.Context, handler ModDeleteHandler) *ModDelete {
	return &ModDelete{Context: ctx, Handler: handler}
}

/*ModDelete swagger:route DELETE /mods/{modID} mod modDelete

Delete a specific mod

*/
type ModDelete struct {
	Context *middleware.Context
	Handler ModDeleteHandler
}

func (o *ModDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewModDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
