// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ModTeamPermHandlerFunc turns a function with the right signature into a mod team perm handler
type ModTeamPermHandlerFunc func(ModTeamPermParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ModTeamPermHandlerFunc) Handle(params ModTeamPermParams) middleware.Responder {
	return fn(params)
}

// ModTeamPermHandler interface for that can handle valid mod team perm params
type ModTeamPermHandler interface {
	Handle(ModTeamPermParams) middleware.Responder
}

// NewModTeamPerm creates a new http.Handler for the mod team perm operation
func NewModTeamPerm(ctx *middleware.Context, handler ModTeamPermHandler) *ModTeamPerm {
	return &ModTeamPerm{Context: ctx, Handler: handler}
}

/*ModTeamPerm swagger:route PUT /mods/{modID}/teams mod modTeamPerm

Update team perms for mod

*/
type ModTeamPerm struct {
	Context *middleware.Context
	Handler ModTeamPermHandler
}

func (o *ModTeamPerm) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewModTeamPermParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
