// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ModUserDeleteHandlerFunc turns a function with the right signature into a mod user delete handler
type ModUserDeleteHandlerFunc func(ModUserDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ModUserDeleteHandlerFunc) Handle(params ModUserDeleteParams) middleware.Responder {
	return fn(params)
}

// ModUserDeleteHandler interface for that can handle valid mod user delete params
type ModUserDeleteHandler interface {
	Handle(ModUserDeleteParams) middleware.Responder
}

// NewModUserDelete creates a new http.Handler for the mod user delete operation
func NewModUserDelete(ctx *middleware.Context, handler ModUserDeleteHandler) *ModUserDelete {
	return &ModUserDelete{Context: ctx, Handler: handler}
}

/*ModUserDelete swagger:route DELETE /mods/{modID}/users mod modUserDelete

Remove a user from mod

*/
type ModUserDelete struct {
	Context *middleware.Context
	Handler ModUserDeleteHandler
}

func (o *ModUserDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewModUserDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
