// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// PermitModTeamHandlerFunc turns a function with the right signature into a permit mod team handler
type PermitModTeamHandlerFunc func(PermitModTeamParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PermitModTeamHandlerFunc) Handle(params PermitModTeamParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PermitModTeamHandler interface for that can handle valid permit mod team params
type PermitModTeamHandler interface {
	Handle(PermitModTeamParams, *models.User) middleware.Responder
}

// NewPermitModTeam creates a new http.Handler for the permit mod team operation
func NewPermitModTeam(ctx *middleware.Context, handler PermitModTeamHandler) *PermitModTeam {
	return &PermitModTeam{Context: ctx, Handler: handler}
}

/* PermitModTeam swagger:route PUT /mods/{mod_id}/teams mod permitModTeam

Update team perms for mod

*/
type PermitModTeam struct {
	Context *middleware.Context
	Handler PermitModTeamHandler
}

func (o *PermitModTeam) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPermitModTeamParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
