// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// UpdateModHandlerFunc turns a function with the right signature into a update mod handler
type UpdateModHandlerFunc func(UpdateModParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateModHandlerFunc) Handle(params UpdateModParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UpdateModHandler interface for that can handle valid update mod params
type UpdateModHandler interface {
	Handle(UpdateModParams, *models.User) middleware.Responder
}

// NewUpdateMod creates a new http.Handler for the update mod operation
func NewUpdateMod(ctx *middleware.Context, handler UpdateModHandler) *UpdateMod {
	return &UpdateMod{Context: ctx, Handler: handler}
}

/*
	UpdateMod swagger:route PUT /mods/{mod_id} mod updateMod

Update a specific mod
*/
type UpdateMod struct {
	Context *middleware.Context
	Handler UpdateModHandler
}

func (o *UpdateMod) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateModParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
