// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// VersionBuildDeleteURL generates an URL for the version build delete operation
type VersionBuildDeleteURL struct {
	ModID     string
	VersionID string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *VersionBuildDeleteURL) WithBasePath(bp string) *VersionBuildDeleteURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *VersionBuildDeleteURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *VersionBuildDeleteURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/mods/{modID}/versions/{versionID}/builds"

	modID := o.ModID
	if modID != "" {
		_path = strings.Replace(_path, "{modID}", modID, -1)
	} else {
		return nil, errors.New("modId is required on VersionBuildDeleteURL")
	}

	versionID := o.VersionID
	if versionID != "" {
		_path = strings.Replace(_path, "{versionID}", versionID, -1)
	} else {
		return nil, errors.New("versionId is required on VersionBuildDeleteURL")
	}

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *VersionBuildDeleteURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *VersionBuildDeleteURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *VersionBuildDeleteURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on VersionBuildDeleteURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on VersionBuildDeleteURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *VersionBuildDeleteURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
