// Code generated by go-swagger; DO NOT EDIT.

package mod

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// VersionCreateHandlerFunc turns a function with the right signature into a version create handler
type VersionCreateHandlerFunc func(VersionCreateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn VersionCreateHandlerFunc) Handle(params VersionCreateParams) middleware.Responder {
	return fn(params)
}

// VersionCreateHandler interface for that can handle valid version create params
type VersionCreateHandler interface {
	Handle(VersionCreateParams) middleware.Responder
}

// NewVersionCreate creates a new http.Handler for the version create operation
func NewVersionCreate(ctx *middleware.Context, handler VersionCreateHandler) *VersionCreate {
	return &VersionCreate{Context: ctx, Handler: handler}
}

/*VersionCreate swagger:route POST /mods/{modID}/versions mod versionCreate

Create a new version for a mod

*/
type VersionCreate struct {
	Context *middleware.Context
	Handler VersionCreateHandler
}

func (o *VersionCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewVersionCreateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
