// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// PermitTeamPackHandlerFunc turns a function with the right signature into a permit team pack handler
type PermitTeamPackHandlerFunc func(PermitTeamPackParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn PermitTeamPackHandlerFunc) Handle(params PermitTeamPackParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// PermitTeamPackHandler interface for that can handle valid permit team pack params
type PermitTeamPackHandler interface {
	Handle(PermitTeamPackParams, *models.User) middleware.Responder
}

// NewPermitTeamPack creates a new http.Handler for the permit team pack operation
func NewPermitTeamPack(ctx *middleware.Context, handler PermitTeamPackHandler) *PermitTeamPack {
	return &PermitTeamPack{Context: ctx, Handler: handler}
}

/* PermitTeamPack swagger:route PUT /teams/{team_id}/packs team permitTeamPack

Update pack perms for team

*/
type PermitTeamPack struct {
	Context *middleware.Context
	Handler PermitTeamPackHandler
}

func (o *PermitTeamPack) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPermitTeamPackParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
