// Code generated by go-swagger; DO NOT EDIT.

package team

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// TeamModDeleteHandlerFunc turns a function with the right signature into a team mod delete handler
type TeamModDeleteHandlerFunc func(TeamModDeleteParams) middleware.Responder

// Handle executing the request and returning a response
func (fn TeamModDeleteHandlerFunc) Handle(params TeamModDeleteParams) middleware.Responder {
	return fn(params)
}

// TeamModDeleteHandler interface for that can handle valid team mod delete params
type TeamModDeleteHandler interface {
	Handle(TeamModDeleteParams) middleware.Responder
}

// NewTeamModDelete creates a new http.Handler for the team mod delete operation
func NewTeamModDelete(ctx *middleware.Context, handler TeamModDeleteHandler) *TeamModDelete {
	return &TeamModDelete{Context: ctx, Handler: handler}
}

/*TeamModDelete swagger:route DELETE /teams/{teamID}/mods team teamModDelete

Remove a mod from team

*/
type TeamModDelete struct {
	Context *middleware.Context
	Handler TeamModDeleteHandler
}

func (o *TeamModDelete) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewTeamModDeleteParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
