// Code generated by go-swagger; DO NOT EDIT.

package pack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// AppendBuildToVersionHandlerFunc turns a function with the right signature into a append build to version handler
type AppendBuildToVersionHandlerFunc func(AppendBuildToVersionParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn AppendBuildToVersionHandlerFunc) Handle(params AppendBuildToVersionParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// AppendBuildToVersionHandler interface for that can handle valid append build to version params
type AppendBuildToVersionHandler interface {
	Handle(AppendBuildToVersionParams, *models.User) middleware.Responder
}

// NewAppendBuildToVersion creates a new http.Handler for the append build to version operation
func NewAppendBuildToVersion(ctx *middleware.Context, handler AppendBuildToVersionHandler) *AppendBuildToVersion {
	return &AppendBuildToVersion{Context: ctx, Handler: handler}
}

/* AppendBuildToVersion swagger:route POST /packs/{pack_id}/builds/{build_id}/versions pack appendBuildToVersion

Assign a version to a build

*/
type AppendBuildToVersion struct {
	Context *middleware.Context
	Handler AppendBuildToVersionHandler
}

func (o *AppendBuildToVersion) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAppendBuildToVersionParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
