// Code generated by go-swagger; DO NOT EDIT.

package pack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// AppendPackToTeamHandlerFunc turns a function with the right signature into a append pack to team handler
type AppendPackToTeamHandlerFunc func(AppendPackToTeamParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn AppendPackToTeamHandlerFunc) Handle(params AppendPackToTeamParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// AppendPackToTeamHandler interface for that can handle valid append pack to team params
type AppendPackToTeamHandler interface {
	Handle(AppendPackToTeamParams, *models.User) middleware.Responder
}

// NewAppendPackToTeam creates a new http.Handler for the append pack to team operation
func NewAppendPackToTeam(ctx *middleware.Context, handler AppendPackToTeamHandler) *AppendPackToTeam {
	return &AppendPackToTeam{Context: ctx, Handler: handler}
}

/*
	AppendPackToTeam swagger:route POST /packs/{pack_id}/teams pack appendPackToTeam

Assign a team to pack
*/
type AppendPackToTeam struct {
	Context *middleware.Context
	Handler AppendPackToTeamHandler
}

func (o *AppendPackToTeam) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAppendPackToTeamParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
