// Code generated by go-swagger; DO NOT EDIT.

package pack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
)

// ListPacksOKCode is the HTTP code returned for type ListPacksOK
const ListPacksOKCode int = 200

/*ListPacksOK A collection of packs

swagger:response listPacksOK
*/
type ListPacksOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Pack `json:"body,omitempty"`
}

// NewListPacksOK creates ListPacksOK with default headers values
func NewListPacksOK() *ListPacksOK {

	return &ListPacksOK{}
}

// WithPayload adds the payload to the list packs o k response
func (o *ListPacksOK) WithPayload(payload []*models.Pack) *ListPacksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list packs o k response
func (o *ListPacksOK) SetPayload(payload []*models.Pack) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPacksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Pack, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListPacksForbiddenCode is the HTTP code returned for type ListPacksForbidden
const ListPacksForbiddenCode int = 403

/*ListPacksForbidden User is not authorized

swagger:response listPacksForbidden
*/
type ListPacksForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewListPacksForbidden creates ListPacksForbidden with default headers values
func NewListPacksForbidden() *ListPacksForbidden {

	return &ListPacksForbidden{}
}

// WithPayload adds the payload to the list packs forbidden response
func (o *ListPacksForbidden) WithPayload(payload *models.GeneralError) *ListPacksForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list packs forbidden response
func (o *ListPacksForbidden) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPacksForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ListPacksDefault Some error unrelated to the handler

swagger:response listPacksDefault
*/
type ListPacksDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewListPacksDefault creates ListPacksDefault with default headers values
func NewListPacksDefault(code int) *ListPacksDefault {
	if code <= 0 {
		code = 500
	}

	return &ListPacksDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the list packs default response
func (o *ListPacksDefault) WithStatusCode(code int) *ListPacksDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the list packs default response
func (o *ListPacksDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the list packs default response
func (o *ListPacksDefault) WithPayload(payload *models.GeneralError) *ListPacksDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list packs default response
func (o *ListPacksDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListPacksDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
