// Code generated by go-swagger; DO NOT EDIT.

package pack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PackIndexHandlerFunc turns a function with the right signature into a pack index handler
type PackIndexHandlerFunc func(PackIndexParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PackIndexHandlerFunc) Handle(params PackIndexParams) middleware.Responder {
	return fn(params)
}

// PackIndexHandler interface for that can handle valid pack index params
type PackIndexHandler interface {
	Handle(PackIndexParams) middleware.Responder
}

// NewPackIndex creates a new http.Handler for the pack index operation
func NewPackIndex(ctx *middleware.Context, handler PackIndexHandler) *PackIndex {
	return &PackIndex{Context: ctx, Handler: handler}
}

/*PackIndex swagger:route GET /packs pack packIndex

Fetch all available packs

*/
type PackIndex struct {
	Context *middleware.Context
	Handler PackIndexHandler
}

func (o *PackIndex) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPackIndexParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
