// Code generated by go-swagger; DO NOT EDIT.

package pack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/kleister/kleister-api/pkg/api/v1/models"
)

// PackUserPermOKCode is the HTTP code returned for type PackUserPermOK
const PackUserPermOKCode int = 200

/*PackUserPermOK Plain success message

swagger:response packUserPermOK
*/
type PackUserPermOK struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPackUserPermOK creates PackUserPermOK with default headers values
func NewPackUserPermOK() *PackUserPermOK {

	return &PackUserPermOK{}
}

// WithPayload adds the payload to the pack user perm o k response
func (o *PackUserPermOK) WithPayload(payload *models.GeneralError) *PackUserPermOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pack user perm o k response
func (o *PackUserPermOK) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PackUserPermOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PackUserPermForbiddenCode is the HTTP code returned for type PackUserPermForbidden
const PackUserPermForbiddenCode int = 403

/*PackUserPermForbidden User is not authorized

swagger:response packUserPermForbidden
*/
type PackUserPermForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPackUserPermForbidden creates PackUserPermForbidden with default headers values
func NewPackUserPermForbidden() *PackUserPermForbidden {

	return &PackUserPermForbidden{}
}

// WithPayload adds the payload to the pack user perm forbidden response
func (o *PackUserPermForbidden) WithPayload(payload *models.GeneralError) *PackUserPermForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pack user perm forbidden response
func (o *PackUserPermForbidden) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PackUserPermForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PackUserPermPreconditionFailedCode is the HTTP code returned for type PackUserPermPreconditionFailed
const PackUserPermPreconditionFailedCode int = 412

/*PackUserPermPreconditionFailed Failed to parse request body

swagger:response packUserPermPreconditionFailed
*/
type PackUserPermPreconditionFailed struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPackUserPermPreconditionFailed creates PackUserPermPreconditionFailed with default headers values
func NewPackUserPermPreconditionFailed() *PackUserPermPreconditionFailed {

	return &PackUserPermPreconditionFailed{}
}

// WithPayload adds the payload to the pack user perm precondition failed response
func (o *PackUserPermPreconditionFailed) WithPayload(payload *models.GeneralError) *PackUserPermPreconditionFailed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pack user perm precondition failed response
func (o *PackUserPermPreconditionFailed) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PackUserPermPreconditionFailed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(412)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PackUserPermUnprocessableEntityCode is the HTTP code returned for type PackUserPermUnprocessableEntity
const PackUserPermUnprocessableEntityCode int = 422

/*PackUserPermUnprocessableEntity User is not assigned

swagger:response packUserPermUnprocessableEntity
*/
type PackUserPermUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPackUserPermUnprocessableEntity creates PackUserPermUnprocessableEntity with default headers values
func NewPackUserPermUnprocessableEntity() *PackUserPermUnprocessableEntity {

	return &PackUserPermUnprocessableEntity{}
}

// WithPayload adds the payload to the pack user perm unprocessable entity response
func (o *PackUserPermUnprocessableEntity) WithPayload(payload *models.GeneralError) *PackUserPermUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pack user perm unprocessable entity response
func (o *PackUserPermUnprocessableEntity) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PackUserPermUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PackUserPermDefault Some error unrelated to the handler

swagger:response packUserPermDefault
*/
type PackUserPermDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.GeneralError `json:"body,omitempty"`
}

// NewPackUserPermDefault creates PackUserPermDefault with default headers values
func NewPackUserPermDefault(code int) *PackUserPermDefault {
	if code <= 0 {
		code = 500
	}

	return &PackUserPermDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the pack user perm default response
func (o *PackUserPermDefault) WithStatusCode(code int) *PackUserPermDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the pack user perm default response
func (o *PackUserPermDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the pack user perm default response
func (o *PackUserPermDefault) WithPayload(payload *models.GeneralError) *PackUserPermDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the pack user perm default response
func (o *PackUserPermDefault) SetPayload(payload *models.GeneralError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PackUserPermDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
