// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/kleister/kleister-api/pkg/api/v1/models"
	"github.com/kleister/kleister-api/pkg/api/v1/restapi/operations/auth"
	"github.com/kleister/kleister-api/pkg/api/v1/restapi/operations/forge"
	"github.com/kleister/kleister-api/pkg/api/v1/restapi/operations/minecraft"
	"github.com/kleister/kleister-api/pkg/api/v1/restapi/operations/mod"
	"github.com/kleister/kleister-api/pkg/api/v1/restapi/operations/pack"
	"github.com/kleister/kleister-api/pkg/api/v1/restapi/operations/profile"
	"github.com/kleister/kleister-api/pkg/api/v1/restapi/operations/team"
	"github.com/kleister/kleister-api/pkg/api/v1/restapi/operations/user"
)

// NewKleisterAPI creates a new Kleister instance
func NewKleisterAPI(spec *loads.Document) *KleisterAPI {
	return &KleisterAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		PackAppendBuildToVersionHandler: pack.AppendBuildToVersionHandlerFunc(func(params pack.AppendBuildToVersionParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.AppendBuildToVersion has not yet been implemented")
		}),
		ForgeAppendForgeToBuildHandler: forge.AppendForgeToBuildHandlerFunc(func(params forge.AppendForgeToBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation forge.AppendForgeToBuild has not yet been implemented")
		}),
		MinecraftAppendMinecraftToBuildHandler: minecraft.AppendMinecraftToBuildHandlerFunc(func(params minecraft.AppendMinecraftToBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation minecraft.AppendMinecraftToBuild has not yet been implemented")
		}),
		ModAppendModToTeamHandler: mod.AppendModToTeamHandlerFunc(func(params mod.AppendModToTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.AppendModToTeam has not yet been implemented")
		}),
		ModAppendModToUserHandler: mod.AppendModToUserHandlerFunc(func(params mod.AppendModToUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.AppendModToUser has not yet been implemented")
		}),
		PackAppendPackToTeamHandler: pack.AppendPackToTeamHandlerFunc(func(params pack.AppendPackToTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.AppendPackToTeam has not yet been implemented")
		}),
		PackAppendPackToUserHandler: pack.AppendPackToUserHandlerFunc(func(params pack.AppendPackToUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.AppendPackToUser has not yet been implemented")
		}),
		TeamAppendTeamToModHandler: team.AppendTeamToModHandlerFunc(func(params team.AppendTeamToModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.AppendTeamToMod has not yet been implemented")
		}),
		TeamAppendTeamToPackHandler: team.AppendTeamToPackHandlerFunc(func(params team.AppendTeamToPackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.AppendTeamToPack has not yet been implemented")
		}),
		TeamAppendTeamToUserHandler: team.AppendTeamToUserHandlerFunc(func(params team.AppendTeamToUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.AppendTeamToUser has not yet been implemented")
		}),
		UserAppendUserToModHandler: user.AppendUserToModHandlerFunc(func(params user.AppendUserToModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.AppendUserToMod has not yet been implemented")
		}),
		UserAppendUserToPackHandler: user.AppendUserToPackHandlerFunc(func(params user.AppendUserToPackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.AppendUserToPack has not yet been implemented")
		}),
		UserAppendUserToTeamHandler: user.AppendUserToTeamHandlerFunc(func(params user.AppendUserToTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.AppendUserToTeam has not yet been implemented")
		}),
		ModAppendVersionToBuildHandler: mod.AppendVersionToBuildHandlerFunc(func(params mod.AppendVersionToBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.AppendVersionToBuild has not yet been implemented")
		}),
		PackCreateBuildHandler: pack.CreateBuildHandlerFunc(func(params pack.CreateBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.CreateBuild has not yet been implemented")
		}),
		ModCreateModHandler: mod.CreateModHandlerFunc(func(params mod.CreateModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.CreateMod has not yet been implemented")
		}),
		PackCreatePackHandler: pack.CreatePackHandlerFunc(func(params pack.CreatePackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.CreatePack has not yet been implemented")
		}),
		TeamCreateTeamHandler: team.CreateTeamHandlerFunc(func(params team.CreateTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.CreateTeam has not yet been implemented")
		}),
		UserCreateUserHandler: user.CreateUserHandlerFunc(func(params user.CreateUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.CreateUser has not yet been implemented")
		}),
		ModCreateVersionHandler: mod.CreateVersionHandlerFunc(func(params mod.CreateVersionParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.CreateVersion has not yet been implemented")
		}),
		PackDeleteBuildHandler: pack.DeleteBuildHandlerFunc(func(params pack.DeleteBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.DeleteBuild has not yet been implemented")
		}),
		PackDeleteBuildFromVersionHandler: pack.DeleteBuildFromVersionHandlerFunc(func(params pack.DeleteBuildFromVersionParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.DeleteBuildFromVersion has not yet been implemented")
		}),
		ForgeDeleteForgeFromBuildHandler: forge.DeleteForgeFromBuildHandlerFunc(func(params forge.DeleteForgeFromBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation forge.DeleteForgeFromBuild has not yet been implemented")
		}),
		MinecraftDeleteMinecraftFromBuildHandler: minecraft.DeleteMinecraftFromBuildHandlerFunc(func(params minecraft.DeleteMinecraftFromBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation minecraft.DeleteMinecraftFromBuild has not yet been implemented")
		}),
		ModDeleteModHandler: mod.DeleteModHandlerFunc(func(params mod.DeleteModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.DeleteMod has not yet been implemented")
		}),
		ModDeleteModFromTeamHandler: mod.DeleteModFromTeamHandlerFunc(func(params mod.DeleteModFromTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.DeleteModFromTeam has not yet been implemented")
		}),
		ModDeleteModFromUserHandler: mod.DeleteModFromUserHandlerFunc(func(params mod.DeleteModFromUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.DeleteModFromUser has not yet been implemented")
		}),
		PackDeletePackHandler: pack.DeletePackHandlerFunc(func(params pack.DeletePackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.DeletePack has not yet been implemented")
		}),
		PackDeletePackFromTeamHandler: pack.DeletePackFromTeamHandlerFunc(func(params pack.DeletePackFromTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.DeletePackFromTeam has not yet been implemented")
		}),
		PackDeletePackFromUserHandler: pack.DeletePackFromUserHandlerFunc(func(params pack.DeletePackFromUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.DeletePackFromUser has not yet been implemented")
		}),
		TeamDeleteTeamHandler: team.DeleteTeamHandlerFunc(func(params team.DeleteTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.DeleteTeam has not yet been implemented")
		}),
		TeamDeleteTeamFromModHandler: team.DeleteTeamFromModHandlerFunc(func(params team.DeleteTeamFromModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.DeleteTeamFromMod has not yet been implemented")
		}),
		TeamDeleteTeamFromPackHandler: team.DeleteTeamFromPackHandlerFunc(func(params team.DeleteTeamFromPackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.DeleteTeamFromPack has not yet been implemented")
		}),
		TeamDeleteTeamFromUserHandler: team.DeleteTeamFromUserHandlerFunc(func(params team.DeleteTeamFromUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.DeleteTeamFromUser has not yet been implemented")
		}),
		UserDeleteUserHandler: user.DeleteUserHandlerFunc(func(params user.DeleteUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.DeleteUser has not yet been implemented")
		}),
		UserDeleteUserFromModHandler: user.DeleteUserFromModHandlerFunc(func(params user.DeleteUserFromModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.DeleteUserFromMod has not yet been implemented")
		}),
		UserDeleteUserFromPackHandler: user.DeleteUserFromPackHandlerFunc(func(params user.DeleteUserFromPackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.DeleteUserFromPack has not yet been implemented")
		}),
		UserDeleteUserFromTeamHandler: user.DeleteUserFromTeamHandlerFunc(func(params user.DeleteUserFromTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.DeleteUserFromTeam has not yet been implemented")
		}),
		ModDeleteVersionHandler: mod.DeleteVersionHandlerFunc(func(params mod.DeleteVersionParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.DeleteVersion has not yet been implemented")
		}),
		ModDeleteVersionFromBuildHandler: mod.DeleteVersionFromBuildHandlerFunc(func(params mod.DeleteVersionFromBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.DeleteVersionFromBuild has not yet been implemented")
		}),
		PackListBuildVersionsHandler: pack.ListBuildVersionsHandlerFunc(func(params pack.ListBuildVersionsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.ListBuildVersions has not yet been implemented")
		}),
		PackListBuildsHandler: pack.ListBuildsHandlerFunc(func(params pack.ListBuildsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.ListBuilds has not yet been implemented")
		}),
		ForgeListForgeBuildsHandler: forge.ListForgeBuildsHandlerFunc(func(params forge.ListForgeBuildsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation forge.ListForgeBuilds has not yet been implemented")
		}),
		ForgeListForgesHandler: forge.ListForgesHandlerFunc(func(params forge.ListForgesParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation forge.ListForges has not yet been implemented")
		}),
		MinecraftListMinecraftBuildsHandler: minecraft.ListMinecraftBuildsHandlerFunc(func(params minecraft.ListMinecraftBuildsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation minecraft.ListMinecraftBuilds has not yet been implemented")
		}),
		MinecraftListMinecraftsHandler: minecraft.ListMinecraftsHandlerFunc(func(params minecraft.ListMinecraftsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation minecraft.ListMinecrafts has not yet been implemented")
		}),
		ModListModTeamsHandler: mod.ListModTeamsHandlerFunc(func(params mod.ListModTeamsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.ListModTeams has not yet been implemented")
		}),
		ModListModUsersHandler: mod.ListModUsersHandlerFunc(func(params mod.ListModUsersParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.ListModUsers has not yet been implemented")
		}),
		ModListModsHandler: mod.ListModsHandlerFunc(func(params mod.ListModsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.ListMods has not yet been implemented")
		}),
		PackListPackTeamsHandler: pack.ListPackTeamsHandlerFunc(func(params pack.ListPackTeamsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.ListPackTeams has not yet been implemented")
		}),
		PackListPackUsersHandler: pack.ListPackUsersHandlerFunc(func(params pack.ListPackUsersParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.ListPackUsers has not yet been implemented")
		}),
		PackListPacksHandler: pack.ListPacksHandlerFunc(func(params pack.ListPacksParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.ListPacks has not yet been implemented")
		}),
		TeamListTeamModsHandler: team.ListTeamModsHandlerFunc(func(params team.ListTeamModsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.ListTeamMods has not yet been implemented")
		}),
		TeamListTeamPacksHandler: team.ListTeamPacksHandlerFunc(func(params team.ListTeamPacksParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.ListTeamPacks has not yet been implemented")
		}),
		TeamListTeamUsersHandler: team.ListTeamUsersHandlerFunc(func(params team.ListTeamUsersParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.ListTeamUsers has not yet been implemented")
		}),
		TeamListTeamsHandler: team.ListTeamsHandlerFunc(func(params team.ListTeamsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.ListTeams has not yet been implemented")
		}),
		UserListUserModsHandler: user.ListUserModsHandlerFunc(func(params user.ListUserModsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.ListUserMods has not yet been implemented")
		}),
		UserListUserPacksHandler: user.ListUserPacksHandlerFunc(func(params user.ListUserPacksParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.ListUserPacks has not yet been implemented")
		}),
		UserListUserTeamsHandler: user.ListUserTeamsHandlerFunc(func(params user.ListUserTeamsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.ListUserTeams has not yet been implemented")
		}),
		UserListUsersHandler: user.ListUsersHandlerFunc(func(params user.ListUsersParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.ListUsers has not yet been implemented")
		}),
		ModListVersionBuildsHandler: mod.ListVersionBuildsHandlerFunc(func(params mod.ListVersionBuildsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.ListVersionBuilds has not yet been implemented")
		}),
		ModListVersionsHandler: mod.ListVersionsHandlerFunc(func(params mod.ListVersionsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.ListVersions has not yet been implemented")
		}),
		AuthLoginUserHandler: auth.LoginUserHandlerFunc(func(params auth.LoginUserParams) middleware.Responder {
			return middleware.NotImplemented("operation auth.LoginUser has not yet been implemented")
		}),
		ModPermitModTeamHandler: mod.PermitModTeamHandlerFunc(func(params mod.PermitModTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.PermitModTeam has not yet been implemented")
		}),
		ModPermitModUserHandler: mod.PermitModUserHandlerFunc(func(params mod.PermitModUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.PermitModUser has not yet been implemented")
		}),
		PackPermitPackTeamHandler: pack.PermitPackTeamHandlerFunc(func(params pack.PermitPackTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.PermitPackTeam has not yet been implemented")
		}),
		PackPermitPackUserHandler: pack.PermitPackUserHandlerFunc(func(params pack.PermitPackUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.PermitPackUser has not yet been implemented")
		}),
		TeamPermitTeamModHandler: team.PermitTeamModHandlerFunc(func(params team.PermitTeamModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.PermitTeamMod has not yet been implemented")
		}),
		TeamPermitTeamPackHandler: team.PermitTeamPackHandlerFunc(func(params team.PermitTeamPackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.PermitTeamPack has not yet been implemented")
		}),
		TeamPermitTeamUserHandler: team.PermitTeamUserHandlerFunc(func(params team.PermitTeamUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.PermitTeamUser has not yet been implemented")
		}),
		UserPermitUserModHandler: user.PermitUserModHandlerFunc(func(params user.PermitUserModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.PermitUserMod has not yet been implemented")
		}),
		UserPermitUserPackHandler: user.PermitUserPackHandlerFunc(func(params user.PermitUserPackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.PermitUserPack has not yet been implemented")
		}),
		UserPermitUserTeamHandler: user.PermitUserTeamHandlerFunc(func(params user.PermitUserTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.PermitUserTeam has not yet been implemented")
		}),
		AuthRefreshAuthHandler: auth.RefreshAuthHandlerFunc(func(params auth.RefreshAuthParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation auth.RefreshAuth has not yet been implemented")
		}),
		ForgeSearchForgesHandler: forge.SearchForgesHandlerFunc(func(params forge.SearchForgesParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation forge.SearchForges has not yet been implemented")
		}),
		MinecraftSearchMinecraftsHandler: minecraft.SearchMinecraftsHandlerFunc(func(params minecraft.SearchMinecraftsParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation minecraft.SearchMinecrafts has not yet been implemented")
		}),
		PackShowBuildHandler: pack.ShowBuildHandlerFunc(func(params pack.ShowBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.ShowBuild has not yet been implemented")
		}),
		ModShowModHandler: mod.ShowModHandlerFunc(func(params mod.ShowModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.ShowMod has not yet been implemented")
		}),
		PackShowPackHandler: pack.ShowPackHandlerFunc(func(params pack.ShowPackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.ShowPack has not yet been implemented")
		}),
		ProfileShowProfileHandler: profile.ShowProfileHandlerFunc(func(params profile.ShowProfileParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation profile.ShowProfile has not yet been implemented")
		}),
		TeamShowTeamHandler: team.ShowTeamHandlerFunc(func(params team.ShowTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.ShowTeam has not yet been implemented")
		}),
		UserShowUserHandler: user.ShowUserHandlerFunc(func(params user.ShowUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.ShowUser has not yet been implemented")
		}),
		ModShowVersionHandler: mod.ShowVersionHandlerFunc(func(params mod.ShowVersionParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.ShowVersion has not yet been implemented")
		}),
		ProfileTokenProfileHandler: profile.TokenProfileHandlerFunc(func(params profile.TokenProfileParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation profile.TokenProfile has not yet been implemented")
		}),
		PackUpdateBuildHandler: pack.UpdateBuildHandlerFunc(func(params pack.UpdateBuildParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.UpdateBuild has not yet been implemented")
		}),
		ForgeUpdateForgeHandler: forge.UpdateForgeHandlerFunc(func(params forge.UpdateForgeParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation forge.UpdateForge has not yet been implemented")
		}),
		MinecraftUpdateMinecraftHandler: minecraft.UpdateMinecraftHandlerFunc(func(params minecraft.UpdateMinecraftParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation minecraft.UpdateMinecraft has not yet been implemented")
		}),
		ModUpdateModHandler: mod.UpdateModHandlerFunc(func(params mod.UpdateModParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.UpdateMod has not yet been implemented")
		}),
		PackUpdatePackHandler: pack.UpdatePackHandlerFunc(func(params pack.UpdatePackParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation pack.UpdatePack has not yet been implemented")
		}),
		ProfileUpdateProfileHandler: profile.UpdateProfileHandlerFunc(func(params profile.UpdateProfileParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation profile.UpdateProfile has not yet been implemented")
		}),
		TeamUpdateTeamHandler: team.UpdateTeamHandlerFunc(func(params team.UpdateTeamParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation team.UpdateTeam has not yet been implemented")
		}),
		UserUpdateUserHandler: user.UpdateUserHandlerFunc(func(params user.UpdateUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation user.UpdateUser has not yet been implemented")
		}),
		ModUpdateVersionHandler: mod.UpdateVersionHandlerFunc(func(params mod.UpdateVersionParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation mod.UpdateVersion has not yet been implemented")
		}),
		AuthVerifyAuthHandler: auth.VerifyAuthHandlerFunc(func(params auth.VerifyAuthParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation auth.VerifyAuth has not yet been implemented")
		}),

		// Applies when the Authorization header is set with the Basic scheme
		BasicAuth: func(user string, pass string) (*models.User, error) {
			return nil, errors.NotImplemented("basic auth  (Basic) has not yet been implemented")
		},
		// Applies when the "X-API-Key" header is set
		HeaderAuth: func(token string) (*models.User, error) {
			return nil, errors.NotImplemented("api key auth (Header) X-API-Key from header param [X-API-Key] has not yet been implemented")
		},
		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*KleisterAPI API definition for Kleister, manage mod packs for Minecraft */
type KleisterAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// BasicAuth registers a function that takes username and password and returns a principal
	// it performs authentication with basic auth
	BasicAuth func(string, string) (*models.User, error)

	// HeaderAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key X-API-Key provided in the header
	HeaderAuth func(string) (*models.User, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// PackAppendBuildToVersionHandler sets the operation handler for the append build to version operation
	PackAppendBuildToVersionHandler pack.AppendBuildToVersionHandler
	// ForgeAppendForgeToBuildHandler sets the operation handler for the append forge to build operation
	ForgeAppendForgeToBuildHandler forge.AppendForgeToBuildHandler
	// MinecraftAppendMinecraftToBuildHandler sets the operation handler for the append minecraft to build operation
	MinecraftAppendMinecraftToBuildHandler minecraft.AppendMinecraftToBuildHandler
	// ModAppendModToTeamHandler sets the operation handler for the append mod to team operation
	ModAppendModToTeamHandler mod.AppendModToTeamHandler
	// ModAppendModToUserHandler sets the operation handler for the append mod to user operation
	ModAppendModToUserHandler mod.AppendModToUserHandler
	// PackAppendPackToTeamHandler sets the operation handler for the append pack to team operation
	PackAppendPackToTeamHandler pack.AppendPackToTeamHandler
	// PackAppendPackToUserHandler sets the operation handler for the append pack to user operation
	PackAppendPackToUserHandler pack.AppendPackToUserHandler
	// TeamAppendTeamToModHandler sets the operation handler for the append team to mod operation
	TeamAppendTeamToModHandler team.AppendTeamToModHandler
	// TeamAppendTeamToPackHandler sets the operation handler for the append team to pack operation
	TeamAppendTeamToPackHandler team.AppendTeamToPackHandler
	// TeamAppendTeamToUserHandler sets the operation handler for the append team to user operation
	TeamAppendTeamToUserHandler team.AppendTeamToUserHandler
	// UserAppendUserToModHandler sets the operation handler for the append user to mod operation
	UserAppendUserToModHandler user.AppendUserToModHandler
	// UserAppendUserToPackHandler sets the operation handler for the append user to pack operation
	UserAppendUserToPackHandler user.AppendUserToPackHandler
	// UserAppendUserToTeamHandler sets the operation handler for the append user to team operation
	UserAppendUserToTeamHandler user.AppendUserToTeamHandler
	// ModAppendVersionToBuildHandler sets the operation handler for the append version to build operation
	ModAppendVersionToBuildHandler mod.AppendVersionToBuildHandler
	// PackCreateBuildHandler sets the operation handler for the create build operation
	PackCreateBuildHandler pack.CreateBuildHandler
	// ModCreateModHandler sets the operation handler for the create mod operation
	ModCreateModHandler mod.CreateModHandler
	// PackCreatePackHandler sets the operation handler for the create pack operation
	PackCreatePackHandler pack.CreatePackHandler
	// TeamCreateTeamHandler sets the operation handler for the create team operation
	TeamCreateTeamHandler team.CreateTeamHandler
	// UserCreateUserHandler sets the operation handler for the create user operation
	UserCreateUserHandler user.CreateUserHandler
	// ModCreateVersionHandler sets the operation handler for the create version operation
	ModCreateVersionHandler mod.CreateVersionHandler
	// PackDeleteBuildHandler sets the operation handler for the delete build operation
	PackDeleteBuildHandler pack.DeleteBuildHandler
	// PackDeleteBuildFromVersionHandler sets the operation handler for the delete build from version operation
	PackDeleteBuildFromVersionHandler pack.DeleteBuildFromVersionHandler
	// ForgeDeleteForgeFromBuildHandler sets the operation handler for the delete forge from build operation
	ForgeDeleteForgeFromBuildHandler forge.DeleteForgeFromBuildHandler
	// MinecraftDeleteMinecraftFromBuildHandler sets the operation handler for the delete minecraft from build operation
	MinecraftDeleteMinecraftFromBuildHandler minecraft.DeleteMinecraftFromBuildHandler
	// ModDeleteModHandler sets the operation handler for the delete mod operation
	ModDeleteModHandler mod.DeleteModHandler
	// ModDeleteModFromTeamHandler sets the operation handler for the delete mod from team operation
	ModDeleteModFromTeamHandler mod.DeleteModFromTeamHandler
	// ModDeleteModFromUserHandler sets the operation handler for the delete mod from user operation
	ModDeleteModFromUserHandler mod.DeleteModFromUserHandler
	// PackDeletePackHandler sets the operation handler for the delete pack operation
	PackDeletePackHandler pack.DeletePackHandler
	// PackDeletePackFromTeamHandler sets the operation handler for the delete pack from team operation
	PackDeletePackFromTeamHandler pack.DeletePackFromTeamHandler
	// PackDeletePackFromUserHandler sets the operation handler for the delete pack from user operation
	PackDeletePackFromUserHandler pack.DeletePackFromUserHandler
	// TeamDeleteTeamHandler sets the operation handler for the delete team operation
	TeamDeleteTeamHandler team.DeleteTeamHandler
	// TeamDeleteTeamFromModHandler sets the operation handler for the delete team from mod operation
	TeamDeleteTeamFromModHandler team.DeleteTeamFromModHandler
	// TeamDeleteTeamFromPackHandler sets the operation handler for the delete team from pack operation
	TeamDeleteTeamFromPackHandler team.DeleteTeamFromPackHandler
	// TeamDeleteTeamFromUserHandler sets the operation handler for the delete team from user operation
	TeamDeleteTeamFromUserHandler team.DeleteTeamFromUserHandler
	// UserDeleteUserHandler sets the operation handler for the delete user operation
	UserDeleteUserHandler user.DeleteUserHandler
	// UserDeleteUserFromModHandler sets the operation handler for the delete user from mod operation
	UserDeleteUserFromModHandler user.DeleteUserFromModHandler
	// UserDeleteUserFromPackHandler sets the operation handler for the delete user from pack operation
	UserDeleteUserFromPackHandler user.DeleteUserFromPackHandler
	// UserDeleteUserFromTeamHandler sets the operation handler for the delete user from team operation
	UserDeleteUserFromTeamHandler user.DeleteUserFromTeamHandler
	// ModDeleteVersionHandler sets the operation handler for the delete version operation
	ModDeleteVersionHandler mod.DeleteVersionHandler
	// ModDeleteVersionFromBuildHandler sets the operation handler for the delete version from build operation
	ModDeleteVersionFromBuildHandler mod.DeleteVersionFromBuildHandler
	// PackListBuildVersionsHandler sets the operation handler for the list build versions operation
	PackListBuildVersionsHandler pack.ListBuildVersionsHandler
	// PackListBuildsHandler sets the operation handler for the list builds operation
	PackListBuildsHandler pack.ListBuildsHandler
	// ForgeListForgeBuildsHandler sets the operation handler for the list forge builds operation
	ForgeListForgeBuildsHandler forge.ListForgeBuildsHandler
	// ForgeListForgesHandler sets the operation handler for the list forges operation
	ForgeListForgesHandler forge.ListForgesHandler
	// MinecraftListMinecraftBuildsHandler sets the operation handler for the list minecraft builds operation
	MinecraftListMinecraftBuildsHandler minecraft.ListMinecraftBuildsHandler
	// MinecraftListMinecraftsHandler sets the operation handler for the list minecrafts operation
	MinecraftListMinecraftsHandler minecraft.ListMinecraftsHandler
	// ModListModTeamsHandler sets the operation handler for the list mod teams operation
	ModListModTeamsHandler mod.ListModTeamsHandler
	// ModListModUsersHandler sets the operation handler for the list mod users operation
	ModListModUsersHandler mod.ListModUsersHandler
	// ModListModsHandler sets the operation handler for the list mods operation
	ModListModsHandler mod.ListModsHandler
	// PackListPackTeamsHandler sets the operation handler for the list pack teams operation
	PackListPackTeamsHandler pack.ListPackTeamsHandler
	// PackListPackUsersHandler sets the operation handler for the list pack users operation
	PackListPackUsersHandler pack.ListPackUsersHandler
	// PackListPacksHandler sets the operation handler for the list packs operation
	PackListPacksHandler pack.ListPacksHandler
	// TeamListTeamModsHandler sets the operation handler for the list team mods operation
	TeamListTeamModsHandler team.ListTeamModsHandler
	// TeamListTeamPacksHandler sets the operation handler for the list team packs operation
	TeamListTeamPacksHandler team.ListTeamPacksHandler
	// TeamListTeamUsersHandler sets the operation handler for the list team users operation
	TeamListTeamUsersHandler team.ListTeamUsersHandler
	// TeamListTeamsHandler sets the operation handler for the list teams operation
	TeamListTeamsHandler team.ListTeamsHandler
	// UserListUserModsHandler sets the operation handler for the list user mods operation
	UserListUserModsHandler user.ListUserModsHandler
	// UserListUserPacksHandler sets the operation handler for the list user packs operation
	UserListUserPacksHandler user.ListUserPacksHandler
	// UserListUserTeamsHandler sets the operation handler for the list user teams operation
	UserListUserTeamsHandler user.ListUserTeamsHandler
	// UserListUsersHandler sets the operation handler for the list users operation
	UserListUsersHandler user.ListUsersHandler
	// ModListVersionBuildsHandler sets the operation handler for the list version builds operation
	ModListVersionBuildsHandler mod.ListVersionBuildsHandler
	// ModListVersionsHandler sets the operation handler for the list versions operation
	ModListVersionsHandler mod.ListVersionsHandler
	// AuthLoginUserHandler sets the operation handler for the login user operation
	AuthLoginUserHandler auth.LoginUserHandler
	// ModPermitModTeamHandler sets the operation handler for the permit mod team operation
	ModPermitModTeamHandler mod.PermitModTeamHandler
	// ModPermitModUserHandler sets the operation handler for the permit mod user operation
	ModPermitModUserHandler mod.PermitModUserHandler
	// PackPermitPackTeamHandler sets the operation handler for the permit pack team operation
	PackPermitPackTeamHandler pack.PermitPackTeamHandler
	// PackPermitPackUserHandler sets the operation handler for the permit pack user operation
	PackPermitPackUserHandler pack.PermitPackUserHandler
	// TeamPermitTeamModHandler sets the operation handler for the permit team mod operation
	TeamPermitTeamModHandler team.PermitTeamModHandler
	// TeamPermitTeamPackHandler sets the operation handler for the permit team pack operation
	TeamPermitTeamPackHandler team.PermitTeamPackHandler
	// TeamPermitTeamUserHandler sets the operation handler for the permit team user operation
	TeamPermitTeamUserHandler team.PermitTeamUserHandler
	// UserPermitUserModHandler sets the operation handler for the permit user mod operation
	UserPermitUserModHandler user.PermitUserModHandler
	// UserPermitUserPackHandler sets the operation handler for the permit user pack operation
	UserPermitUserPackHandler user.PermitUserPackHandler
	// UserPermitUserTeamHandler sets the operation handler for the permit user team operation
	UserPermitUserTeamHandler user.PermitUserTeamHandler
	// AuthRefreshAuthHandler sets the operation handler for the refresh auth operation
	AuthRefreshAuthHandler auth.RefreshAuthHandler
	// ForgeSearchForgesHandler sets the operation handler for the search forges operation
	ForgeSearchForgesHandler forge.SearchForgesHandler
	// MinecraftSearchMinecraftsHandler sets the operation handler for the search minecrafts operation
	MinecraftSearchMinecraftsHandler minecraft.SearchMinecraftsHandler
	// PackShowBuildHandler sets the operation handler for the show build operation
	PackShowBuildHandler pack.ShowBuildHandler
	// ModShowModHandler sets the operation handler for the show mod operation
	ModShowModHandler mod.ShowModHandler
	// PackShowPackHandler sets the operation handler for the show pack operation
	PackShowPackHandler pack.ShowPackHandler
	// ProfileShowProfileHandler sets the operation handler for the show profile operation
	ProfileShowProfileHandler profile.ShowProfileHandler
	// TeamShowTeamHandler sets the operation handler for the show team operation
	TeamShowTeamHandler team.ShowTeamHandler
	// UserShowUserHandler sets the operation handler for the show user operation
	UserShowUserHandler user.ShowUserHandler
	// ModShowVersionHandler sets the operation handler for the show version operation
	ModShowVersionHandler mod.ShowVersionHandler
	// ProfileTokenProfileHandler sets the operation handler for the token profile operation
	ProfileTokenProfileHandler profile.TokenProfileHandler
	// PackUpdateBuildHandler sets the operation handler for the update build operation
	PackUpdateBuildHandler pack.UpdateBuildHandler
	// ForgeUpdateForgeHandler sets the operation handler for the update forge operation
	ForgeUpdateForgeHandler forge.UpdateForgeHandler
	// MinecraftUpdateMinecraftHandler sets the operation handler for the update minecraft operation
	MinecraftUpdateMinecraftHandler minecraft.UpdateMinecraftHandler
	// ModUpdateModHandler sets the operation handler for the update mod operation
	ModUpdateModHandler mod.UpdateModHandler
	// PackUpdatePackHandler sets the operation handler for the update pack operation
	PackUpdatePackHandler pack.UpdatePackHandler
	// ProfileUpdateProfileHandler sets the operation handler for the update profile operation
	ProfileUpdateProfileHandler profile.UpdateProfileHandler
	// TeamUpdateTeamHandler sets the operation handler for the update team operation
	TeamUpdateTeamHandler team.UpdateTeamHandler
	// UserUpdateUserHandler sets the operation handler for the update user operation
	UserUpdateUserHandler user.UpdateUserHandler
	// ModUpdateVersionHandler sets the operation handler for the update version operation
	ModUpdateVersionHandler mod.UpdateVersionHandler
	// AuthVerifyAuthHandler sets the operation handler for the verify auth operation
	AuthVerifyAuthHandler auth.VerifyAuthHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *KleisterAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *KleisterAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *KleisterAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *KleisterAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *KleisterAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *KleisterAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *KleisterAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *KleisterAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *KleisterAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the KleisterAPI
func (o *KleisterAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BasicAuth == nil {
		unregistered = append(unregistered, "BasicAuth")
	}
	if o.HeaderAuth == nil {
		unregistered = append(unregistered, "XAPIKeyAuth")
	}

	if o.PackAppendBuildToVersionHandler == nil {
		unregistered = append(unregistered, "pack.AppendBuildToVersionHandler")
	}
	if o.ForgeAppendForgeToBuildHandler == nil {
		unregistered = append(unregistered, "forge.AppendForgeToBuildHandler")
	}
	if o.MinecraftAppendMinecraftToBuildHandler == nil {
		unregistered = append(unregistered, "minecraft.AppendMinecraftToBuildHandler")
	}
	if o.ModAppendModToTeamHandler == nil {
		unregistered = append(unregistered, "mod.AppendModToTeamHandler")
	}
	if o.ModAppendModToUserHandler == nil {
		unregistered = append(unregistered, "mod.AppendModToUserHandler")
	}
	if o.PackAppendPackToTeamHandler == nil {
		unregistered = append(unregistered, "pack.AppendPackToTeamHandler")
	}
	if o.PackAppendPackToUserHandler == nil {
		unregistered = append(unregistered, "pack.AppendPackToUserHandler")
	}
	if o.TeamAppendTeamToModHandler == nil {
		unregistered = append(unregistered, "team.AppendTeamToModHandler")
	}
	if o.TeamAppendTeamToPackHandler == nil {
		unregistered = append(unregistered, "team.AppendTeamToPackHandler")
	}
	if o.TeamAppendTeamToUserHandler == nil {
		unregistered = append(unregistered, "team.AppendTeamToUserHandler")
	}
	if o.UserAppendUserToModHandler == nil {
		unregistered = append(unregistered, "user.AppendUserToModHandler")
	}
	if o.UserAppendUserToPackHandler == nil {
		unregistered = append(unregistered, "user.AppendUserToPackHandler")
	}
	if o.UserAppendUserToTeamHandler == nil {
		unregistered = append(unregistered, "user.AppendUserToTeamHandler")
	}
	if o.ModAppendVersionToBuildHandler == nil {
		unregistered = append(unregistered, "mod.AppendVersionToBuildHandler")
	}
	if o.PackCreateBuildHandler == nil {
		unregistered = append(unregistered, "pack.CreateBuildHandler")
	}
	if o.ModCreateModHandler == nil {
		unregistered = append(unregistered, "mod.CreateModHandler")
	}
	if o.PackCreatePackHandler == nil {
		unregistered = append(unregistered, "pack.CreatePackHandler")
	}
	if o.TeamCreateTeamHandler == nil {
		unregistered = append(unregistered, "team.CreateTeamHandler")
	}
	if o.UserCreateUserHandler == nil {
		unregistered = append(unregistered, "user.CreateUserHandler")
	}
	if o.ModCreateVersionHandler == nil {
		unregistered = append(unregistered, "mod.CreateVersionHandler")
	}
	if o.PackDeleteBuildHandler == nil {
		unregistered = append(unregistered, "pack.DeleteBuildHandler")
	}
	if o.PackDeleteBuildFromVersionHandler == nil {
		unregistered = append(unregistered, "pack.DeleteBuildFromVersionHandler")
	}
	if o.ForgeDeleteForgeFromBuildHandler == nil {
		unregistered = append(unregistered, "forge.DeleteForgeFromBuildHandler")
	}
	if o.MinecraftDeleteMinecraftFromBuildHandler == nil {
		unregistered = append(unregistered, "minecraft.DeleteMinecraftFromBuildHandler")
	}
	if o.ModDeleteModHandler == nil {
		unregistered = append(unregistered, "mod.DeleteModHandler")
	}
	if o.ModDeleteModFromTeamHandler == nil {
		unregistered = append(unregistered, "mod.DeleteModFromTeamHandler")
	}
	if o.ModDeleteModFromUserHandler == nil {
		unregistered = append(unregistered, "mod.DeleteModFromUserHandler")
	}
	if o.PackDeletePackHandler == nil {
		unregistered = append(unregistered, "pack.DeletePackHandler")
	}
	if o.PackDeletePackFromTeamHandler == nil {
		unregistered = append(unregistered, "pack.DeletePackFromTeamHandler")
	}
	if o.PackDeletePackFromUserHandler == nil {
		unregistered = append(unregistered, "pack.DeletePackFromUserHandler")
	}
	if o.TeamDeleteTeamHandler == nil {
		unregistered = append(unregistered, "team.DeleteTeamHandler")
	}
	if o.TeamDeleteTeamFromModHandler == nil {
		unregistered = append(unregistered, "team.DeleteTeamFromModHandler")
	}
	if o.TeamDeleteTeamFromPackHandler == nil {
		unregistered = append(unregistered, "team.DeleteTeamFromPackHandler")
	}
	if o.TeamDeleteTeamFromUserHandler == nil {
		unregistered = append(unregistered, "team.DeleteTeamFromUserHandler")
	}
	if o.UserDeleteUserHandler == nil {
		unregistered = append(unregistered, "user.DeleteUserHandler")
	}
	if o.UserDeleteUserFromModHandler == nil {
		unregistered = append(unregistered, "user.DeleteUserFromModHandler")
	}
	if o.UserDeleteUserFromPackHandler == nil {
		unregistered = append(unregistered, "user.DeleteUserFromPackHandler")
	}
	if o.UserDeleteUserFromTeamHandler == nil {
		unregistered = append(unregistered, "user.DeleteUserFromTeamHandler")
	}
	if o.ModDeleteVersionHandler == nil {
		unregistered = append(unregistered, "mod.DeleteVersionHandler")
	}
	if o.ModDeleteVersionFromBuildHandler == nil {
		unregistered = append(unregistered, "mod.DeleteVersionFromBuildHandler")
	}
	if o.PackListBuildVersionsHandler == nil {
		unregistered = append(unregistered, "pack.ListBuildVersionsHandler")
	}
	if o.PackListBuildsHandler == nil {
		unregistered = append(unregistered, "pack.ListBuildsHandler")
	}
	if o.ForgeListForgeBuildsHandler == nil {
		unregistered = append(unregistered, "forge.ListForgeBuildsHandler")
	}
	if o.ForgeListForgesHandler == nil {
		unregistered = append(unregistered, "forge.ListForgesHandler")
	}
	if o.MinecraftListMinecraftBuildsHandler == nil {
		unregistered = append(unregistered, "minecraft.ListMinecraftBuildsHandler")
	}
	if o.MinecraftListMinecraftsHandler == nil {
		unregistered = append(unregistered, "minecraft.ListMinecraftsHandler")
	}
	if o.ModListModTeamsHandler == nil {
		unregistered = append(unregistered, "mod.ListModTeamsHandler")
	}
	if o.ModListModUsersHandler == nil {
		unregistered = append(unregistered, "mod.ListModUsersHandler")
	}
	if o.ModListModsHandler == nil {
		unregistered = append(unregistered, "mod.ListModsHandler")
	}
	if o.PackListPackTeamsHandler == nil {
		unregistered = append(unregistered, "pack.ListPackTeamsHandler")
	}
	if o.PackListPackUsersHandler == nil {
		unregistered = append(unregistered, "pack.ListPackUsersHandler")
	}
	if o.PackListPacksHandler == nil {
		unregistered = append(unregistered, "pack.ListPacksHandler")
	}
	if o.TeamListTeamModsHandler == nil {
		unregistered = append(unregistered, "team.ListTeamModsHandler")
	}
	if o.TeamListTeamPacksHandler == nil {
		unregistered = append(unregistered, "team.ListTeamPacksHandler")
	}
	if o.TeamListTeamUsersHandler == nil {
		unregistered = append(unregistered, "team.ListTeamUsersHandler")
	}
	if o.TeamListTeamsHandler == nil {
		unregistered = append(unregistered, "team.ListTeamsHandler")
	}
	if o.UserListUserModsHandler == nil {
		unregistered = append(unregistered, "user.ListUserModsHandler")
	}
	if o.UserListUserPacksHandler == nil {
		unregistered = append(unregistered, "user.ListUserPacksHandler")
	}
	if o.UserListUserTeamsHandler == nil {
		unregistered = append(unregistered, "user.ListUserTeamsHandler")
	}
	if o.UserListUsersHandler == nil {
		unregistered = append(unregistered, "user.ListUsersHandler")
	}
	if o.ModListVersionBuildsHandler == nil {
		unregistered = append(unregistered, "mod.ListVersionBuildsHandler")
	}
	if o.ModListVersionsHandler == nil {
		unregistered = append(unregistered, "mod.ListVersionsHandler")
	}
	if o.AuthLoginUserHandler == nil {
		unregistered = append(unregistered, "auth.LoginUserHandler")
	}
	if o.ModPermitModTeamHandler == nil {
		unregistered = append(unregistered, "mod.PermitModTeamHandler")
	}
	if o.ModPermitModUserHandler == nil {
		unregistered = append(unregistered, "mod.PermitModUserHandler")
	}
	if o.PackPermitPackTeamHandler == nil {
		unregistered = append(unregistered, "pack.PermitPackTeamHandler")
	}
	if o.PackPermitPackUserHandler == nil {
		unregistered = append(unregistered, "pack.PermitPackUserHandler")
	}
	if o.TeamPermitTeamModHandler == nil {
		unregistered = append(unregistered, "team.PermitTeamModHandler")
	}
	if o.TeamPermitTeamPackHandler == nil {
		unregistered = append(unregistered, "team.PermitTeamPackHandler")
	}
	if o.TeamPermitTeamUserHandler == nil {
		unregistered = append(unregistered, "team.PermitTeamUserHandler")
	}
	if o.UserPermitUserModHandler == nil {
		unregistered = append(unregistered, "user.PermitUserModHandler")
	}
	if o.UserPermitUserPackHandler == nil {
		unregistered = append(unregistered, "user.PermitUserPackHandler")
	}
	if o.UserPermitUserTeamHandler == nil {
		unregistered = append(unregistered, "user.PermitUserTeamHandler")
	}
	if o.AuthRefreshAuthHandler == nil {
		unregistered = append(unregistered, "auth.RefreshAuthHandler")
	}
	if o.ForgeSearchForgesHandler == nil {
		unregistered = append(unregistered, "forge.SearchForgesHandler")
	}
	if o.MinecraftSearchMinecraftsHandler == nil {
		unregistered = append(unregistered, "minecraft.SearchMinecraftsHandler")
	}
	if o.PackShowBuildHandler == nil {
		unregistered = append(unregistered, "pack.ShowBuildHandler")
	}
	if o.ModShowModHandler == nil {
		unregistered = append(unregistered, "mod.ShowModHandler")
	}
	if o.PackShowPackHandler == nil {
		unregistered = append(unregistered, "pack.ShowPackHandler")
	}
	if o.ProfileShowProfileHandler == nil {
		unregistered = append(unregistered, "profile.ShowProfileHandler")
	}
	if o.TeamShowTeamHandler == nil {
		unregistered = append(unregistered, "team.ShowTeamHandler")
	}
	if o.UserShowUserHandler == nil {
		unregistered = append(unregistered, "user.ShowUserHandler")
	}
	if o.ModShowVersionHandler == nil {
		unregistered = append(unregistered, "mod.ShowVersionHandler")
	}
	if o.ProfileTokenProfileHandler == nil {
		unregistered = append(unregistered, "profile.TokenProfileHandler")
	}
	if o.PackUpdateBuildHandler == nil {
		unregistered = append(unregistered, "pack.UpdateBuildHandler")
	}
	if o.ForgeUpdateForgeHandler == nil {
		unregistered = append(unregistered, "forge.UpdateForgeHandler")
	}
	if o.MinecraftUpdateMinecraftHandler == nil {
		unregistered = append(unregistered, "minecraft.UpdateMinecraftHandler")
	}
	if o.ModUpdateModHandler == nil {
		unregistered = append(unregistered, "mod.UpdateModHandler")
	}
	if o.PackUpdatePackHandler == nil {
		unregistered = append(unregistered, "pack.UpdatePackHandler")
	}
	if o.ProfileUpdateProfileHandler == nil {
		unregistered = append(unregistered, "profile.UpdateProfileHandler")
	}
	if o.TeamUpdateTeamHandler == nil {
		unregistered = append(unregistered, "team.UpdateTeamHandler")
	}
	if o.UserUpdateUserHandler == nil {
		unregistered = append(unregistered, "user.UpdateUserHandler")
	}
	if o.ModUpdateVersionHandler == nil {
		unregistered = append(unregistered, "mod.UpdateVersionHandler")
	}
	if o.AuthVerifyAuthHandler == nil {
		unregistered = append(unregistered, "auth.VerifyAuthHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *KleisterAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *KleisterAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {
		case "Basic":
			result[name] = o.BasicAuthenticator(func(username, password string) (interface{}, error) {
				return o.BasicAuth(username, password)
			})

		case "Header":
			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.HeaderAuth(token)
			})

		}
	}
	return result
}

// Authorizer returns the registered authorizer
func (o *KleisterAPI) Authorizer() runtime.Authorizer {
	return o.APIAuthorizer
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *KleisterAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *KleisterAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *KleisterAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the kleister API
func (o *KleisterAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *KleisterAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/packs/{pack_id}/builds/{build_id}/versions"] = pack.NewAppendBuildToVersion(o.context, o.PackAppendBuildToVersionHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/forge/{forge_id}/builds"] = forge.NewAppendForgeToBuild(o.context, o.ForgeAppendForgeToBuildHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/minecraft/{minecraft_id}/builds"] = minecraft.NewAppendMinecraftToBuild(o.context, o.MinecraftAppendMinecraftToBuildHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/mods/{mod_id}/teams"] = mod.NewAppendModToTeam(o.context, o.ModAppendModToTeamHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/mods/{mod_id}/users"] = mod.NewAppendModToUser(o.context, o.ModAppendModToUserHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/packs/{pack_id}/teams"] = pack.NewAppendPackToTeam(o.context, o.PackAppendPackToTeamHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/packs/{pack_id}/users"] = pack.NewAppendPackToUser(o.context, o.PackAppendPackToUserHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/teams/{team_id}/mods"] = team.NewAppendTeamToMod(o.context, o.TeamAppendTeamToModHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/teams/{team_id}/packs"] = team.NewAppendTeamToPack(o.context, o.TeamAppendTeamToPackHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/teams/{team_id}/users"] = team.NewAppendTeamToUser(o.context, o.TeamAppendTeamToUserHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users/{user_id}/mods"] = user.NewAppendUserToMod(o.context, o.UserAppendUserToModHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users/{user_id}/packs"] = user.NewAppendUserToPack(o.context, o.UserAppendUserToPackHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users/{user_id}/teams"] = user.NewAppendUserToTeam(o.context, o.UserAppendUserToTeamHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/mods/{mod_id}/versions/{version_id}/builds"] = mod.NewAppendVersionToBuild(o.context, o.ModAppendVersionToBuildHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/packs/{pack_id}/builds"] = pack.NewCreateBuild(o.context, o.PackCreateBuildHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/mods"] = mod.NewCreateMod(o.context, o.ModCreateModHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/packs"] = pack.NewCreatePack(o.context, o.PackCreatePackHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/teams"] = team.NewCreateTeam(o.context, o.TeamCreateTeamHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/users"] = user.NewCreateUser(o.context, o.UserCreateUserHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/mods/{mod_id}/versions"] = mod.NewCreateVersion(o.context, o.ModCreateVersionHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/packs/{pack_id}/builds/{build_id}"] = pack.NewDeleteBuild(o.context, o.PackDeleteBuildHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/packs/{pack_id}/builds/{build_id}/versions"] = pack.NewDeleteBuildFromVersion(o.context, o.PackDeleteBuildFromVersionHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/forge/{forge_id}/builds"] = forge.NewDeleteForgeFromBuild(o.context, o.ForgeDeleteForgeFromBuildHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/minecraft/{minecraft_id}/builds"] = minecraft.NewDeleteMinecraftFromBuild(o.context, o.MinecraftDeleteMinecraftFromBuildHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/mods/{mod_id}"] = mod.NewDeleteMod(o.context, o.ModDeleteModHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/mods/{mod_id}/teams"] = mod.NewDeleteModFromTeam(o.context, o.ModDeleteModFromTeamHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/mods/{mod_id}/users"] = mod.NewDeleteModFromUser(o.context, o.ModDeleteModFromUserHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/packs/{pack_id}"] = pack.NewDeletePack(o.context, o.PackDeletePackHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/packs/{pack_id}/teams"] = pack.NewDeletePackFromTeam(o.context, o.PackDeletePackFromTeamHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/packs/{pack_id}/users"] = pack.NewDeletePackFromUser(o.context, o.PackDeletePackFromUserHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/teams/{team_id}"] = team.NewDeleteTeam(o.context, o.TeamDeleteTeamHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/teams/{team_id}/mods"] = team.NewDeleteTeamFromMod(o.context, o.TeamDeleteTeamFromModHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/teams/{team_id}/packs"] = team.NewDeleteTeamFromPack(o.context, o.TeamDeleteTeamFromPackHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/teams/{team_id}/users"] = team.NewDeleteTeamFromUser(o.context, o.TeamDeleteTeamFromUserHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{user_id}"] = user.NewDeleteUser(o.context, o.UserDeleteUserHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{user_id}/mods"] = user.NewDeleteUserFromMod(o.context, o.UserDeleteUserFromModHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{user_id}/packs"] = user.NewDeleteUserFromPack(o.context, o.UserDeleteUserFromPackHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/users/{user_id}/teams"] = user.NewDeleteUserFromTeam(o.context, o.UserDeleteUserFromTeamHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/mods/{mod_id}/versions/{version_id}"] = mod.NewDeleteVersion(o.context, o.ModDeleteVersionHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/mods/{mod_id}/versions/{version_id}/builds"] = mod.NewDeleteVersionFromBuild(o.context, o.ModDeleteVersionFromBuildHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/packs/{pack_id}/builds/{build_id}/versions"] = pack.NewListBuildVersions(o.context, o.PackListBuildVersionsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/packs/{pack_id}/builds"] = pack.NewListBuilds(o.context, o.PackListBuildsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/forge/{forge_id}/builds"] = forge.NewListForgeBuilds(o.context, o.ForgeListForgeBuildsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/forge"] = forge.NewListForges(o.context, o.ForgeListForgesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/minecraft/{minecraft_id}/builds"] = minecraft.NewListMinecraftBuilds(o.context, o.MinecraftListMinecraftBuildsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/minecraft"] = minecraft.NewListMinecrafts(o.context, o.MinecraftListMinecraftsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/mods/{mod_id}/teams"] = mod.NewListModTeams(o.context, o.ModListModTeamsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/mods/{mod_id}/users"] = mod.NewListModUsers(o.context, o.ModListModUsersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/mods"] = mod.NewListMods(o.context, o.ModListModsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/packs/{pack_id}/teams"] = pack.NewListPackTeams(o.context, o.PackListPackTeamsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/packs/{pack_id}/users"] = pack.NewListPackUsers(o.context, o.PackListPackUsersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/packs"] = pack.NewListPacks(o.context, o.PackListPacksHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/teams/{team_id}/mods"] = team.NewListTeamMods(o.context, o.TeamListTeamModsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/teams/{team_id}/packs"] = team.NewListTeamPacks(o.context, o.TeamListTeamPacksHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/teams/{team_id}/users"] = team.NewListTeamUsers(o.context, o.TeamListTeamUsersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/teams"] = team.NewListTeams(o.context, o.TeamListTeamsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{user_id}/mods"] = user.NewListUserMods(o.context, o.UserListUserModsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{user_id}/packs"] = user.NewListUserPacks(o.context, o.UserListUserPacksHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{user_id}/teams"] = user.NewListUserTeams(o.context, o.UserListUserTeamsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users"] = user.NewListUsers(o.context, o.UserListUsersHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/mods/{mod_id}/versions/{version_id}/builds"] = mod.NewListVersionBuilds(o.context, o.ModListVersionBuildsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/mods/{mod_id}/versions"] = mod.NewListVersions(o.context, o.ModListVersionsHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/auth/login"] = auth.NewLoginUser(o.context, o.AuthLoginUserHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/mods/{mod_id}/teams"] = mod.NewPermitModTeam(o.context, o.ModPermitModTeamHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/mods/{mod_id}/users"] = mod.NewPermitModUser(o.context, o.ModPermitModUserHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/packs/{pack_id}/teams"] = pack.NewPermitPackTeam(o.context, o.PackPermitPackTeamHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/packs/{pack_id}/users"] = pack.NewPermitPackUser(o.context, o.PackPermitPackUserHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/teams/{team_id}/mods"] = team.NewPermitTeamMod(o.context, o.TeamPermitTeamModHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/teams/{team_id}/packs"] = team.NewPermitTeamPack(o.context, o.TeamPermitTeamPackHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/teams/{team_id}/users"] = team.NewPermitTeamUser(o.context, o.TeamPermitTeamUserHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/users/{user_id}/mods"] = user.NewPermitUserMod(o.context, o.UserPermitUserModHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/users/{user_id}/packs"] = user.NewPermitUserPack(o.context, o.UserPermitUserPackHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/users/{user_id}/teams"] = user.NewPermitUserTeam(o.context, o.UserPermitUserTeamHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/auth/refresh"] = auth.NewRefreshAuth(o.context, o.AuthRefreshAuthHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/forge/{forge_id}"] = forge.NewSearchForges(o.context, o.ForgeSearchForgesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/minecraft/{minecraft_id}"] = minecraft.NewSearchMinecrafts(o.context, o.MinecraftSearchMinecraftsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/packs/{pack_id}/builds/{build_id}"] = pack.NewShowBuild(o.context, o.PackShowBuildHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/mods/{mod_id}"] = mod.NewShowMod(o.context, o.ModShowModHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/packs/{pack_id}"] = pack.NewShowPack(o.context, o.PackShowPackHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/profile/self"] = profile.NewShowProfile(o.context, o.ProfileShowProfileHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/teams/{team_id}"] = team.NewShowTeam(o.context, o.TeamShowTeamHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/users/{user_id}"] = user.NewShowUser(o.context, o.UserShowUserHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/mods/{mod_id}/versions/{version_id}"] = mod.NewShowVersion(o.context, o.ModShowVersionHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/profile/token"] = profile.NewTokenProfile(o.context, o.ProfileTokenProfileHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/packs/{pack_id}/builds/{build_id}"] = pack.NewUpdateBuild(o.context, o.PackUpdateBuildHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/forge"] = forge.NewUpdateForge(o.context, o.ForgeUpdateForgeHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/minecraft"] = minecraft.NewUpdateMinecraft(o.context, o.MinecraftUpdateMinecraftHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/mods/{mod_id}"] = mod.NewUpdateMod(o.context, o.ModUpdateModHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/packs/{pack_id}"] = pack.NewUpdatePack(o.context, o.PackUpdatePackHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/profile/self"] = profile.NewUpdateProfile(o.context, o.ProfileUpdateProfileHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/teams/{team_id}"] = team.NewUpdateTeam(o.context, o.TeamUpdateTeamHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/users/{user_id}"] = user.NewUpdateUser(o.context, o.UserUpdateUserHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/mods/{mod_id}/versions/{version_id}"] = mod.NewUpdateVersion(o.context, o.ModUpdateVersionHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/auth/verify"] = auth.NewVerifyAuth(o.context, o.AuthVerifyAuthHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *KleisterAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *KleisterAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *KleisterAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *KleisterAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *KleisterAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
